import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // 'en' or 'vi'

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'vi' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    nav_home: 'HOME',
    nav_timeline: 'TIMELINE',
    nav_register: 'REGISTER',
    hero_title: 'HAEVTHON',
    hero_subtitle: 'The premier arena for AI innovators. Architect, build, and scale Agentic Systems that solve real-world challenges.',
    hero_cta_register: 'Register Now',
    hero_cta_explore: 'Explore Tracks',
    innovation_badge: 'OUR IMPACT',
    innovation_title: 'Driving the Innovation Wave in Vietnam',
    innovation_desc: 'Vietnam is rapidly emerging as a global hub for AI development. Haevthon 2024 is designed to empower local talent to build world-class Agentic Solutions.',
    innovation_highlight1_title: 'Catalyzing Growth',
    innovation_highlight1_desc: 'Hackathons are the engine of rapid prototyping, turning wild ideas into viable startups within 48 hours.',
    innovation_highlight2_title: "Vietnam's AI Era",
    innovation_highlight2_desc: 'With a booming tech ecosystem, Vietnam is rapidly becoming Southeast Asia\'s powerhouse for AI and automation.',
    innovation_highlight3_title: 'Building the Future',
    innovation_highlight3_desc: 'Haevthon is more than a competition; it\'s a movement to empower the next generation of Vietnamese builders.',
    innovation_stat1_label: 'AI Growth',
    innovation_stat1_desc: 'Annual growth in AI adoption',
    innovation_stat2_label: 'Startups',
    innovation_stat2_desc: 'New AI-driven tech startups',
    innovation_stat3_label: 'Talent',
    innovation_stat3_desc: 'Skilled developers joining the AI wave',
    tracks_title: 'CHALLENGE TRACKS',
    tracks_subtitle: 'Choose your path and build the future of Agentic Intelligence.',
    track1_title: 'AI Agents with Aevum',
    track1_desc: 'Build intelligent Agent systems and AI Workflows, optimizing autonomous operations.',
    track2_title: 'Workflow & Automation',
    track2_desc: 'Automate complex processes, creating powerful Ops and Internal Tools.',
    track3_title: 'Marketplace / Platform',
    track3_desc: 'Systems for connecting, trading, and coordinating services on the Aevum platform.',
    track4_title: 'Wildcard Innovation',
    track4_desc: 'Any breakthrough ideas using Aevum core infrastructure. Unlimited creativity.',
    track5_title: 'Data Intelligence',
    track5_desc: 'Build AI-powered analytics, data pipelines, and intelligent insights systems on top of Aevum.',
    track6_title: 'Open Source & Community',
    track6_desc: 'Create tools, SDKs, or frameworks that contribute back to the Aevum open-source ecosystem.',
    aevum_edge_title: 'THE AEVUM EDGE',
    aevum_edge_subtitle: 'Build on the infrastructure that defines the future of AI Agent collaboration.',
    feature_squad_title: 'Squad Mode (v1.5)',
    feature_squad_desc: 'Orchestrate multiple specialized agents. Seamless handoffs, collaborative huddles, and squad-wide knowledge sync.',
    feature_pipernet_title: 'PiperNet Hub',
    feature_pipernet_desc: 'Connect to a global network of agentic intelligence. Broadcast procedures and solve architectural bottlenecks at scale.',
    feature_memory_title: 'Living Memory',
    feature_memory_desc: 'Agents that never forget. Persistent context and Vibe Profiling that adapts to your unique architectural style.',
    edge5_title: 'Autonomous Handshake',
    edge5_desc: 'Seamless peer-to-peer protocols for agent-to-agent collaboration and task delegation.',
    edge6_title: 'Quantum State Sync',
    edge6_desc: 'Instantaneous resonance across distributed agentic clusters with zero-latency state persistence.',
    edge7_title: 'Neural Governance',
    edge7_desc: 'An ethics-first framework for autonomous decision-making and secure agentic compliance.',
    edge8_title: 'Bio-inspired Logic',
    edge8_desc: 'Mimicking evolutionary intelligence to create highly adaptive, self-healing agentic swarms.',
    testimonial_title: 'Community Resonance',
    testimonial1_quote: 'The most thoughtfully designed agentic infrastructure I have ever used. Sleek, reliable, and truly innovative.',
    testimonial1_author: 'Senior AI Architect',
    testimonial2_quote: 'Squad Mode changed everything. The level of collaboration between agents feels like magic.',
    testimonial2_author: 'Full-stack Builder',
    testimonial3_quote: 'PiperNet integration is a game changer for distributed teams. The speed of coordination is unmatched.',
    testimonial3_author: 'Team Lead @ DevScale',
    testimonial4_quote: "Aevum's Living Memory is the missing piece for truly autonomous AI collaboration.",
    testimonial4_author: 'Open-source Contributor',
    vision_title: 'OUR MISSION',
    vision_desc: 'Haevthon is not just a coding competition, it is a **Product Factory**. We look for true Builders capable of turning ideas into working MVPs in hours.',
    vision_p1_title: 'Builder-first',
    vision_p1_desc: "We don't judge 'good ideas'. We judge buildability and execution.",
    vision_p2_title: 'Product-first',
    vision_p2_desc: 'Every team must aim for a real product with clear User Flow.',
    vision_p3_title: 'Tool-centric',
    vision_p3_desc: 'Aevum is the default infrastructure. Optimizing Aevum brings scoring advantages.',
    vision_scoring_title: 'SCORING FRAMEWORK',
    incentives_title: 'BEYOND THE PRIZE',
    incentives_subtitle: 'True value for a Builder career',
    incentive1_title: 'Funding & Incubation',
    incentive1_desc: 'Access investment capital and join post-hackathon product acceleration programs.',
    incentive2_title: 'Job & Internship',
    incentive2_desc: 'Internship and employment opportunities at leading tech projects in the I2FLabs ecosystem.',
    incentive3_title: 'Feature Integration',
    incentive3_desc: 'Your product has the chance to be integrated directly into Aevum core system.',
    cta_compete_title: 'READY TO COMPETE?',
    cta_compete_desc: 'Limited spots available to ensure mentor quality and technical support.',
    cta_apply_now: 'Apply Now',
    partners_title: 'STRATEGIC PARTNERS',
    innovation_highlight1_title: 'Catalyzing Growth',
    innovation_highlight1_desc: 'Hackathons are the engine of rapid prototyping, turning wild ideas into viable startups within 48 hours.',
    innovation_highlight2_title: "Vietnam's AI Era",
    innovation_highlight2_desc: 'With a booming tech ecosystem, Vietnam is rapidly becoming Southeast Asia\'s powerhouse for AI and automation.',
    innovation_highlight3_title: 'Building the Future',
    innovation_highlight3_desc: 'Haevthon is more than a competition; it\'s a movement to empower the next generation of Vietnamese builders.',
    innovation_stats_believe: 'Of Vietnam\'s Top Tech Talents Believe AI is the Future.',
    innovation_effect_title: 'THE HACKATHON EFFECT',
    innovation_effect_desc: 'Statistics show that participants of intensive hackathons are 4x more likely to secure leadership roles in tech startups within 12 months of the event.',
    innovation_vision_cta: 'Learn About Our Vision',
    timeline_page_title: 'Event Journey',
    timeline_page_subtitle: 'Follow the path of innovation',
    timeline_phase0_title: 'Phase 0: Pre-Hackathon',
    timeline_phase0_desc: 'Early bird registration and technical readiness. Join our community and prepare your environment for the challenge ahead.',
    timeline_phase0_date: '7–14 days before',
    timeline_phase0_location: 'Online / Aevum PiperNet',
    timeline_phase0_items: [
      { time: '08:00 AM', title: 'Registration Open', detail: 'Secure your spot in the premier agentic hackathon. Limited seats available for elite builders.' },
      { time: '10:00 AM', title: 'FAQ & Support Window', detail: 'Continuous Q&A channel for technical inquiries, rule clarifications, and pre-event guidance.' },
      { time: '02:00 PM', title: 'Meetup & Rules Briefing', detail: 'Virtual orientation to walk through the technical rules, scoring matrix, and Aevum integration requirements.' },
      { time: '04:00 PM', title: 'Workshop: Aevum Onboarding', detail: 'Deep dive into the Aevum Core API, Squad Mode orchestration, and local environment setup.' },
      { time: '06:00 PM', title: 'Team Formation matching', detail: 'Individual matching support for devs, designers, and product thinkers to find their perfect crew.' }
    ],
    timeline_phase1_title: 'Phase 1: Kickoff',
    timeline_phase1_desc: 'The official start of Haevthon. Team formations are finalized and the core challenges are revealed by our mentors.',
    timeline_phase1_date: 'Day 0',
    timeline_phase1_location: 'Main Stage @ Innovation Hub',
    timeline_phase1_items: [
      { time: '09:00 AM', title: 'Opening Ceremony', detail: 'Keynote from I2FLabs architects and the reveal of the 2024 grand theme.' },
      { time: '10:00 AM', title: 'Aevum Ecosystem Intro', detail: 'Overview of Aevum as a core build infrastructure and introduction to the dev squad.', isSpecial: true },
      { time: '10:30 AM', title: 'Problem Reveal', detail: 'Detailed briefing on the core challenges and edge cases you need to solve.' },
      { time: '11:30 AM', title: 'Project Initialization', detail: 'Defining solution direction and phasc-ing out the initial MVP architecture.' }
    ],
    timeline_phase2_title: 'Phase 2: Build Sprint',
    timeline_phase2_desc: 'Intensive 48-hour development cycle. Focus on architecting your agentic systems with the Aevum infrastructure.',
    timeline_phase2_date: '24–48 Hours',
    timeline_phase2_location: 'Hacker Den / Remote',
    timeline_phase2_items: [
      { time: '12:00 PM', title: 'Build Start', detail: 'The 48-hour sprint begins. Live technical support and mentor huddles are active.' },
      { time: '04:00 PM', title: 'Energy Buff Session', detail: 'High-energy boost talks and rapid feedback to keep the momentum during the first 6 hours.', isSpecial: true },
      { time: '08:00 PM', title: 'Checkpoint Support Loop', detail: 'Mandatory technical check-ins to ensure your agentic flow is stable and scaling correctly.' },
      { time: '11:00 PM', title: 'Builder Energy Talk', detail: 'Lightning talks from mentor guests on avoiding over-engineering and using Aevum for speed.', isSpecial: true }
    ],
    timeline_phase3_title: 'Phase 3: Demo Day',
    timeline_phase3_desc: 'Final showdown. Present your product to the panel of judges and the global community for scoring and awards.',
    timeline_phase3_date: 'Final Day',
    timeline_phase3_location: 'Grand Ballroom @ Tech City',
    timeline_phase3_items: [
      { time: '09:00 AM', title: 'Demo Presentations', detail: 'Live demonstration of your working MVP. 5 minutes per team followed by Q&A.' },
      { time: '11:00 AM', title: 'Judge Feedback Loop', detail: 'Deep dive discussions with judges on product viability and architecture quality.', isSpecial: true },
      { time: '02:00 PM', title: 'Real-time Scoring', detail: 'Judges evaluation using the Aevum resonance and product viability metrics.' },
      { time: '04:00 PM', title: 'Award Ceremony', detail: 'Recognition of the top builders and distribution of the $50,000+ prize pool.' }
    ],
    reg_title: 'Join',
    reg_subtitle: 'Register to become a true Builder.',
    reg_label_name: 'Full Name',
    reg_placeholder_name: 'John Doe',
    reg_label_email: 'Email',
    reg_placeholder_email: 'john@example.com',
    reg_label_role: 'Role',
    reg_placeholder_role: 'Select...',
    reg_label_experience: 'Experience',
    reg_placeholder_experience: 'Select...',
    reg_label_interest: 'Project Direction',
    reg_placeholder_interest: 'Briefly share your ideas or skills...',
    reg_btn_submit: 'Confirm Registration',
    reg_btn_submitting: 'Submitting...',
    reg_success: 'Registration successful! Welcome to Haevthon. 🚀',
    reg_success_title: 'Application Received',
    reg_success_desc: 'Thank you for joining Haevthon. Our team will review your profile and contact you soon via email.',
    reg_btn_close: 'Close',
    err_name_min: 'Full name must be at least 2 characters',
    err_email_invalid: 'Invalid email',
    err_role_required: 'Please select a role',
    err_experience_required: 'Please select an experience level',
    err_interest_min: 'Please describe your direction in more detail (at least 10 characters)',
    powered_by: 'Powered By Aevum',
    stats_prizepool: 'Prize Pool',
    stats_format: 'Format',
    stats_timeline: 'Timeline',
    stats_format_val: 'Hybrid / Global',
    stats_timeline_val: 'Coming Soon',
    status_upcoming: 'Upcoming',
    status_active: 'Live',
    status_done: 'Completed',
    nav_sponsors: 'SPONSORS',
    sponsors_partnership_opp: 'PARTNERSHIP OPPORTUNITY',
    sponsors_hero_title1: 'POWER THE',
    sponsors_hero_title2: 'AGENTIC',
    sponsors_hero_title3: 'REVOLUTION',
    sponsors_hero_desc: 'Haevthon 2026 is where the next generation of autonomous AI systems are born. Partner with us and position yourself or your brand at the frontier of agentic intelligence.',
    sponsors_hero_btn: 'BECOME A SPONSOR',
    sponsors_hosted_by: 'HOSTED BY',
    sponsors_org_committee: 'ORGANIZING COMMITTEE',
    sponsors_obj_title: 'OUR SHARED VISION',
    sponsors_obj_heading: 'SHAPING THE FUTURE',
    sponsors_obj_desc: 'Haevthon 2026 is more than a hackathon; it is a strategic launchpad. We are looking for partners who share our vision to push the boundaries of autonomous AI. Together, we provide the resources, platform, and mentorship needed to turn ambitious concepts into reality.',
    sponsors_obj_list1_title: 'Shape the Technology',
    sponsors_obj_list1_desc: 'Collaborate to establish new standards and frameworks for Agentic AI systems.',
    sponsors_obj_list2_title: 'Nurture Talent',
    sponsors_obj_list2_desc: 'Gain direct access to and support a curated network of elite engineers and researchers.',
    sponsors_obj_list3_title: 'Accelerate Innovation',
    sponsors_obj_list3_desc: 'Help turn breakthrough ideas into production-ready products immediately.',
    sponsors_unikorn_desc: 'Strategic Partner. Empowering the next generation of builders.',
    sponsors_i2flabs_desc: 'Primary Organizer & Innovation Hub. Driving the future of agentic technologies.',
    sponsors_aevum_desc: 'Co-Host & Technology Partner. The underlying foundation for autonomous AI systems.',
    sponsors_stats_title: 'BY THE NUMBERS',
    sponsors_why_title: 'WHY PARTNER WITH US',
    sponsors_why_label1: 'Elite Builders',
    sponsors_why_desc1: 'Top developers, designers, and AI researchers in one room.',
    sponsors_why_label2: 'Prize Pool',
    sponsors_why_desc2: 'Serious competitors building production-ready agentic products.',
    sponsors_why_label3: 'Build Sprint',
    sponsors_why_desc3: 'Intense format generating real, working MVPs — not just pitches.',
    sponsors_why_label4: 'Agentic Focus',
    sponsors_why_desc4: 'The most specialized AI hackathon in Southeast Asia.',
    sponsors_contact_title: 'GET IN TOUCH',
    sponsors_contact_heading1: 'LET\'S BUILD',
    sponsors_contact_heading2: 'TOGETHER',
    sponsors_contact_desc: 'Interested in sponsoring Haevthon 2026? Reach out and our partnership team will connect with you within 24 hours to discuss the best package for you or your organization.',
    sponsors_form_success_title: 'Inquiry Received',
    sponsors_form_success_desc: 'Thank you for your interest. Our team will reach out within 24 hours.',
    sponsors_form_name: 'Your Name',
    sponsors_form_name_ph: 'Nguyen Van A',
    sponsors_form_company: 'Company / Organization (Optional)',
    sponsors_form_company_ph: 'Acme Corp / Individual Sponsor',
    sponsors_form_email: 'Email',
    sponsors_form_email_ph: 'partner@company.com',
    sponsors_form_interest: 'Partnership Interest',
    sponsors_form_interest_ph: 'Tell us about your sponsorship interest and budget range...',
    sponsors_form_submit: 'SEND INQUIRY'
  },
  vi: {
    nav_home: 'TRANG CHỦ',
    nav_timeline: 'LỘ TRÌNH',
    nav_register: 'ĐĂNG KÝ',
    hero_title: 'HAEVTHON',
    hero_subtitle: 'Sân chơi hàng đầu cho các nhà đổi mới AI. Thiết kế, xây dựng và mở rộng các Hệ thống Tác tử giải quyết thách thức thực tế.',
    hero_cta_register: 'Đăng Ký Ngay',
    hero_cta_explore: 'Khám Phá Các Track',
    innovation_badge: 'TẦM ẢNH HƯỞNG',
    innovation_title: 'Thúc Đẩy Làn Sóng Đổi Mới Tại Việt Nam',
    innovation_desc: 'Việt Nam đang nhanh chóng trở thành trung tâm phát triển AI toàn cầu. Haevthon 2024 được thiết kế để tiếp sức cho tài năng Việt xây dựng các Giải pháp Tác tử đẳng cấp thế giới.',
    innovation_highlight1_title: 'Thúc Đẩy Tăng Trưởng',
    innovation_highlight1_desc: 'Hackathon là động cơ tạo mẫu nhanh, biến các ý tưởng táo bạo thành các startup tiềm năng chỉ trong 48 giờ.',
    innovation_highlight2_title: "Kỷ Nguyên AI Việt Nam",
    innovation_highlight2_desc: 'Với hệ sinh thái công nghệ đang bùng nổ, Việt Nam đang nhanh chóng trở thành cường quốc AI và tự động hóa tại Đông Nam Á.',
    innovation_highlight3_title: 'Xây Dựng Tương Lai',
    innovation_highlight3_desc: 'Haevthon không chỉ là một cuộc thi; đó là một phong trào để tiếp sức cho thế hệ những nhà xây dựng Việt Nam tiếp theo.',
    innovation_stat1_label: 'Tăng Trưởng AI',
    innovation_stat1_desc: 'Tăng trưởng ứng dụng AI hàng năm',
    innovation_stat2_label: 'Startup',
    innovation_stat2_desc: 'Các công ty khởi nghiệp AI mới',
    innovation_stat3_label: 'Nhân Tài',
    innovation_stat3_desc: 'Lập trình viên tài năng gia nhập làn sóng AI',
    tracks_title: 'CÁC LĨNH VỰC THỬ THÁCH',
    tracks_subtitle: 'Chọn con đường của bạn và xây dựng tương lai của Trí tuệ Tác tử.',
    track1_title: 'Tác Tử AI với Aevum',
    track1_desc: 'Xây dựng hệ thống Agent và AI Workflow thông minh, tối ưu hóa khả năng tự vận hành.',
    track2_title: 'Quy Trình & Tự Động Hóa',
    track2_desc: 'Tự động hóa các quy trình phức tạp, tạo ra các công cụ Ops và Internal Tools mạnh mẽ.',
    track3_title: 'Nền Tảng / Chợ Ứng Dụng',
    track3_desc: 'Hệ thống kết nối, giao dịch và điều phối dịch vụ trên nền tảng Aevum.',
    track4_title: 'Sáng Tạo Đột Phá',
    track4_desc: 'Mọi ý tưởng đột phá sử dụng lõi hạ tầng Aevum. Không giới hạn sự sáng tạo.',
    track5_title: 'Dữ Liệu Thông Minh',
    track5_desc: 'Xây dựng hệ thống phân tích AI, data pipeline và insights thông minh trên nền tảng Aevum.',
    track6_title: 'Nguồn Mở & Cộng Đồng',
    track6_desc: 'Tạo ra các công cụ, SDK hoặc framework đóng góp vào hệ sinh thái mã nguồn mở của Aevum.',
    aevum_edge_title: 'SỨC MẠNH TỪ AEVUM',
    aevum_edge_subtitle: 'Xây dựng trên nền tảng hạ tầng định hình tương lai của sự cộng tác giữa các Tác tử AI.',
    feature_squad_title: 'Chế Độ Squad (v1.5)',
    feature_squad_desc: 'Điều phối nhiều tác tử chuyên biệt. Bàn giao công việc mượt mà, hội ý nhóm và đồng bộ tri thức toàn đội.',
    feature_pipernet_title: 'Mạng Lưới PiperNet',
    feature_pipernet_desc: 'Kết nối với mạng lưới trí tuệ tác tử toàn cầu. Phổ biến quy trình và giải quyết các nút thắt kiến trúc ở quy mô lớn.',
    feature_memory_title: 'Bộ Nhớ Vĩnh Cửu',
    feature_memory_desc: 'Các tác tử không bao giờ quên. Bối cảnh dự án được bảo toàn và hồ sơ Vibe Profiling thích nghi với phong cách riêng của bạn.',
    edge5_title: 'Bắt Tay Tự Hành',
    edge5_desc: 'Giao thức ngang hàng mượt mà cho sự cộng tác và ủy thác nhiệm vụ giữa các tác tử.',
    edge6_title: 'Đồng Bộ Trạng Thái',
    edge6_desc: 'Cộng hưởng tức thì trên các cụm tác tử phân tán với khả năng bảo toàn trạng thái không độ trễ.',
    edge7_title: 'Quản Trị Neural',
    edge7_desc: 'Khung quy tắc ưu tiên đạo đức cho việc ra quyết định tự động và tuân thủ tác tử an toàn.',
    edge8_title: 'Logic Sinh Học',
    edge8_desc: 'Mô phỏng trí tuệ tiến hóa để tạo ra các bầy đàn tác tử có khả năng thích nghi và tự chữa lành cao.',
    testimonial_title: 'Tiếng Vang Cộng Đồng',
    testimonial1_quote: 'Hạ tầng tác tử được thiết kế tỉ mỉ nhất mà tôi từng sử dụng. Sang trọng, tin cậy và thực sự đột phá.',
    testimonial1_author: 'Kiến trúc sư AI Cao cấp',
    testimonial2_quote: 'Squad Mode đã thay đổi tất cả. Cấp độ cộng tác giữa các tác tử thực sự mang lại cảm giác như phép màu.',
    testimonial2_author: 'Nhà phát triển Full-stack',
    testimonial3_quote: 'Tích hợp PiperNet là một bước ngoặt cho các đội ngũ làm việc phân tán. Tốc độ điều phối thực sự vô đối.',
    testimonial3_author: 'Trưởng nhóm tại DevScale',
    testimonial4_quote: 'Bộ nhớ vĩnh cửu của Aevum là mảnh ghép còn thiếu cho sự cộng tác AI thực sự tự chủ.',
    testimonial4_author: 'Người đóng góp mã nguồn mở',
    vision_title: 'SỨ MỆNH CỦA CHÚNG TÔI',
    vision_desc: 'Haevthon không chỉ là một cuộc thi code, mà là một **Product Factory**. Chúng tôi tìm kiếm những Builder thực thụ có khả năng biến ý tưởng thành MVP chạy được chỉ trong vài giờ.',
    vision_p1_title: 'Ưu tiên Builder',
    vision_p1_desc: "Chúng tôi không chấm 'ý tưởng hay'. Chúng tôi chấm độ thực thi và vận hành thực tế.",
    vision_p2_title: 'Ưu tiên Sản phẩm',
    vision_p2_desc: 'Mọi đội thi phải hướng tới sản phẩm thực tế, có luồng người dùng (User Flow) rõ ràng.',
    vision_p3_title: 'Trọng tâm Công cụ',
    vision_p3_desc: 'Aevum là hạ tầng mặc định. Tối ưu hóa Aevum mang lại lợi thế về điểm số.',
    vision_scoring_title: 'KHUNG ĐIỂM ĐÁNH GIÁ',
    incentives_title: 'HƠN CẢ GIẢI THƯỞNG',
    incentives_subtitle: 'Giá trị thực cho sự nghiệp của một Builder',
    incentive1_title: 'Vốn đầu tư & Ươm tạo',
    incentive1_desc: 'Tiếp cận nguồn vốn đầu tư và tham gia chương trình tăng tốc sản phẩm sau Hackathon.',
    incentive2_title: 'Việc làm & Thực tập',
    incentive2_desc: 'Cơ hội thực tập và làm việc tại các dự án công nghệ hàng đầu trong hệ sinh thái I2FLabs.',
    incentive3_title: 'Tích hợp Tính năng',
    incentive3_desc: 'Sản phẩm của bạn có cơ hội được tích hợp trực tiếp vào lõi hệ thống của Aevum.',
    cta_compete_title: 'BẠN ĐÃ SẴN SÀNG?',
    cta_compete_desc: 'Số lượng tham gia có hạn để đảm bảo chất lượng mentor và hỗ trợ kỹ thuật tốt nhất.',
    cta_apply_now: 'Đăng ký ngay',
    partners_title: 'ĐỐI TÁC CHIẾN LƯỢC',
    innovation_highlight1_title: 'Thúc Đẩy Tăng Trưởng',
    innovation_highlight1_desc: 'Hackathon là động cơ tạo mẫu nhanh, biến các ý tưởng táo bạo thành các startup tiềm năng chỉ trong 48 giờ.',
    innovation_highlight2_title: "Kỷ Nguyên AI Việt Nam",
    innovation_highlight2_desc: 'Với hệ sinh thái công nghệ đang bùng nổ, Việt Nam đang nhanh chóng trở thành cường quốc AI và tự động hóa tại Đông Nam Á.',
    innovation_highlight3_title: 'Xây Dựng Tương Lai',
    innovation_highlight3_desc: 'Haevthon không chỉ là một cuộc thi; đó là một phong trào để tiếp sức cho thế hệ những nhà xây dựng Việt Nam tiếp theo.',
    innovation_stats_believe: 'Nhân Tài Công Nghệ Việt Nam Tin Rằng AI Chính Là Tương Lai.',
    innovation_effect_title: 'HIỆU ỨNG HACKATHON',
    innovation_effect_desc: 'Thống kê cho thấy những người tham gia hackathon cường độ cao có khả năng đảm nhận các vai trò lãnh đạo tại các startup công nghệ cao gấp 4 lần trong vòng 12 tháng sau sự kiện.',
    innovation_vision_cta: 'Tìm Hiểu Về Tầm Nhìn',
    timeline_page_title: 'Hành Trình Sự Kiện',
    timeline_page_subtitle: 'Theo dấu con đường của sự đổi mới',
    timeline_phase0_title: 'Giai Đoạn 0: Tiền Sự Kiện',
    timeline_phase0_desc: 'Giai đoạn đăng ký sớm và chuẩn bị kỹ thuật. Gia nhập cộng đồng và thiết lập môi trường để sẵn sàng cho thử thách.',
    timeline_phase0_date: '7–14 ngày trước',
    timeline_phase0_location: 'Trực tuyến / Aevum PiperNet',
    timeline_phase0_items: [
      { time: '08:00 SA', title: 'Mở cổng đăng ký', detail: 'Giành suất tham gia hackathon tác tử hàng đầu. Số lượng giới hạn cho các builder xuất sắc.' },
      { time: '10:00 SA', title: 'FAQ & Hỗ trợ kỹ thuật', detail: 'Kênh hỏi đáp liên tục để giải đáp thắc mắc về luật thi, kỹ thuật và định hướng sản phẩm.' },
      { time: '02:00 CH', title: 'Meetup & Phổ biến luật thi', detail: 'Buổi định hướng trực tuyến để tìm hiểu về luật lệ kỹ thuật, khung điểm và yêu cầu tích hợp Aevum.' },
      { time: '04:00 CH', title: 'Workshop: Đào tạo Aevum', detail: 'Đi sâu vào Aevum Core API, điều phối Squad Mode và thiết lập môi trường lập trình.' },
      { time: '06:00 CH', title: 'Hỗ trợ ghép đội thi', detail: 'Hỗ trợ kết nối Dev, Designer và Product Owner để hình thành đội ngũ thiện chiến nhất.' }
    ],
    timeline_phase1_title: 'Giai Đoạn 1: Khởi Động',
    timeline_phase1_desc: 'Khai mạc chính thức Haevthon. Chốt danh sách đội ngũ và công bố các bài toán hóc búa từ đội ngũ mentor.',
    timeline_phase1_date: 'Ngày 0',
    timeline_phase1_location: 'Sân khấu chính @ Innovation Hub',
    timeline_phase1_items: [
      { time: '09:00 SA', title: 'Lễ khai mạc', detail: 'Bài phát biểu từ các kiến trúc sư I2FLabs và công bố chủ đề lớn của năm 2024.' },
      { time: '10:00 SA', title: 'Giới thiệu Hệ sinh thái Aevum', detail: 'Cái nhìn tổng quan về Aevum như một hạ tầng build core và ra mắt đội ngũ hỗ trợ.', isSpecial: true },
      { time: '10:30 SA', title: 'Công bố đề bài', detail: 'Phổ biến chi tiết về các thử thách cốt lõi và các trường hợp biên bạn cần giải quyết.' },
      { time: '11:30 SA', title: 'Khởi tạo dự án Sprint', detail: 'Xác định hướng giải pháp và phác thảo kiến trúc MVP ban đầu.' }
    ],
    timeline_phase2_title: 'Giai Đoạn 2: Xây Dựng',
    timeline_phase2_desc: 'Chu kỳ phát triển 48 giờ cường độ cao. Tập trung thiết kế hệ thống tác tử trên nền tảng hạ tầng Aevum.',
    timeline_phase2_date: '24–48 Giờ',
    timeline_phase2_location: 'Khu vực Builder / Từ xa',
    timeline_phase2_items: [
      { time: '12:00 CH', title: 'Bắt đầu xây dựng', detail: 'Bắt đầu cuộc đua 48 giờ. Đội ngũ hỗ trợ kỹ thuật và mentor luôn sẵn sàng đồng hành.' },
      { time: '04:00 CH', title: 'Phiên Energy Buff', detail: 'Các buổi truyền lửa và phản hồi nhanh để giữ nhịp độ trong 6 giờ đầu tiên.', isSpecial: true },
      { time: '08:00 CH', title: 'Vòng lặp Checkpoint hỗ trợ', detail: 'Các buổi kiểm tra kỹ thuật bắt buộc để đảm bảo luồng tác tử của bạn ổn định và mở rộng đúng hướng.' },
      { time: '11:00 CH', title: 'Builder Energy Talk', detail: 'Chia sẻ từ các Mentor về cách tránh over-engineering và dùng Aevum để tăng tốc.', isSpecial: true }
    ],
    timeline_phase3_title: 'Giai Đoạn 3: Demo Day',
    timeline_phase3_desc: 'Vòng chung kết. Thuyết trình sản phẩm trước ban giám khảo và cộng đồng toàn cầu để nhận điểm và giải thưởng.',
    timeline_phase3_date: 'Ngày Cuối',
    timeline_phase3_location: 'Hội trường lớn @ Tech City',
    timeline_phase3_items: [
      { time: '09:00 SA', title: 'Thuyết trình Demo', detail: 'Trình diễn trực tiếp sản phẩm MVP. 5 phút cho mỗi đội kèm theo phần hỏi đáp.' },
      { time: '11:00 SA', title: 'Vòng phản hồi từ BGK', detail: 'Thảo luận sâu với ban giám khảo về tính khả thi của sản phẩm và chất lượng kiến trúc.', isSpecial: true },
      { time: '02:00 CH', title: 'Chấm điểm thời gian thực', detail: 'Ban giám khảo đánh giá dựa trên tiêu chuẩn cộng hưởng Aevum và tính khả thi của sản phẩm.' },
      { time: '04:00 CH', title: 'Lễ trao giải', detail: 'Vinh danh những nhà xây dựng hàng đầu và trao thưởng từ tổng quỹ hơn $50,000.' }
    ],
    reg_title: 'Tham gia',
    reg_subtitle: 'Đăng ký để trở thành một Builder thực thụ.',
    reg_label_name: 'Họ và Tên',
    reg_placeholder_name: 'Nguyễn Văn A',
    reg_label_email: 'Email',
    reg_placeholder_email: 'an@haevthon.com',
    reg_label_role: 'Vai trò',
    reg_placeholder_role: 'Chọn...',
    reg_label_experience: 'Kinh nghiệm',
    reg_placeholder_experience: 'Chọn...',
    reg_label_interest: 'Định hướng dự án',
    reg_placeholder_interest: 'Chia sẻ ngắn gọn về ý tưởng hoặc kỹ năng bạn muốn đóng góp...',
    reg_btn_submit: 'Xác nhận Đăng ký',
    reg_btn_submitting: 'Đang gửi...',
    reg_success: 'Đăng ký thành công! Chào mừng bạn đến với Haevthon. 🚀',
    reg_success_title: 'Đã Nhận Đơn Đăng Ký',
    reg_success_desc: 'Cảm ơn bạn đã tham gia Haevthon. Đội ngũ của chúng tôi sẽ xem xét hồ sơ và liên hệ với bạn qua email trong thời gian sớm nhất.',
    reg_btn_close: 'Đóng',
    err_name_min: 'Họ tên phải có ít nhất 2 ký tự',
    err_email_invalid: 'Email không hợp lệ',
    err_role_required: 'Vui lòng chọn một vai trò',
    err_experience_required: 'Vui lòng chọn cấp độ kinh nghiệm',
    err_interest_min: 'Vui lòng mô tả chi tiết hơn định hướng của bạn (ít nhất 10 ký tự)',
    powered_by: 'Phát Triển Bởi Aevum',
    stats_prizepool: 'Tổng Giải Thưởng',
    stats_format: 'Hình Thức',
    stats_timeline: 'Lịch Trình',
    stats_format_val: 'Hybrid / Toàn Cầu',
    stats_timeline_val: 'Sắp Ra Mắt',
    status_upcoming: 'Sắp diễn ra',
    status_active: 'Đang diễn ra',
    status_done: 'Đã kết thúc',
    nav_sponsors: 'NHÀ TÀI TRỢ',
    sponsors_partnership_opp: 'CƠ HỘI HỢP TÁC',
    sponsors_hero_title1: 'KIẾN TẠO',
    sponsors_hero_title2: 'KỶ NGUYÊN',
    sponsors_hero_title3: 'AI AGENT',
    sponsors_hero_desc: 'Haevthon 2026 là nơi thế hệ hệ thống AI tự chủ tiếp theo ra đời. Trở thành đối tác và khẳng định vị thế thương hiệu của bạn tại tiền tuyến của trí tuệ nhân tạo Agentic.',
    sponsors_hero_btn: 'TRỞ THÀNH NHÀ TÀI TRỢ',
    sponsors_hosted_by: 'ĐƠN VỊ TỔ CHỨC',
    sponsors_org_committee: 'BAN TỔ CHỨC',
    sponsors_obj_title: 'TẦM NHÌN CHUNG',
    sponsors_obj_heading: 'KIẾN TẠO TƯƠNG LAI',
    sponsors_obj_desc: 'Haevthon 2026 không chỉ là một cuộc thi, mà là một bệ phóng chiến lược. Chúng tôi tìm kiếm những đối tác có chung tầm nhìn để phá vỡ mọi giới hạn của AI tự chủ. Cùng nhau, chúng ta sẽ cung cấp tài nguyên, nền tảng và sự cố vấn cần thiết để hiện thực hóa những tham vọng lớn lao nhất.',
    sponsors_obj_list1_title: 'Định hình Công nghệ',
    sponsors_obj_list1_desc: 'Hợp tác thiết lập các tiêu chuẩn và framework mới cho hệ thống AI Agentic.',
    sponsors_obj_list2_title: 'Ươm mầm Tài năng',
    sponsors_obj_list2_desc: 'Tiếp cận trực tiếp và hỗ trợ mạng lưới những kỹ sư và nhà nghiên cứu tinh hoa.',
    sponsors_obj_list3_title: 'Đẩy mạnh Đổi mới',
    sponsors_obj_list3_desc: 'Góp phần biến những ý tưởng đột phá thành sản phẩm thực tế có tính ứng dụng cao.',
    sponsors_unikorn_desc: 'Đối tác Chiến lược. Tiếp sức cho thế hệ nhà kiến tạo tương lai.',
    sponsors_i2flabs_desc: 'Đơn vị Tổ chức & Trung tâm Đổi mới. Dẫn dắt tương lai công nghệ Agentic.',
    sponsors_aevum_desc: 'Đồng Tổ chức & Đối tác Công nghệ. Nền tảng lõi cho các hệ thống AI tự chủ.',
    sponsors_stats_title: 'NHỮNG CON SỐ',
    sponsors_why_title: 'TẠI SAO NÊN ĐỒNG HÀNH',
    sponsors_why_label1: 'Kỹ sư Tinh hoa',
    sponsors_why_desc1: 'Quy tụ những lập trình viên, nhà thiết kế và nhà nghiên cứu AI hàng đầu.',
    sponsors_why_label2: 'Tổng Giải thưởng',
    sponsors_why_desc2: 'Các đội thi nghiêm túc xây dựng sản phẩm AI Agent thực tế.',
    sponsors_why_label3: 'Giờ Lập trình',
    sponsors_why_desc3: 'Định dạng cường độ cao tạo ra MVP thực tế — không chỉ là ý tưởng.',
    sponsors_why_label4: 'Tập trung AI Agent',
    sponsors_why_desc4: 'Cuộc thi Hackathon chuyên sâu về AI nhất Đông Nam Á.',
    sponsors_contact_title: 'LIÊN HỆ',
    sponsors_contact_heading1: 'CÙNG NHAU',
    sponsors_contact_heading2: 'KIẾN TẠO',
    sponsors_contact_desc: 'Quan tâm đến việc tài trợ Haevthon 2026? Hãy liên hệ và đội ngũ đối tác của chúng tôi sẽ kết nối với bạn trong vòng 24 giờ để thảo luận về gói tài trợ phù hợp nhất.',
    sponsors_form_success_title: 'Đã Nhận Thông Tin',
    sponsors_form_success_desc: 'Cảm ơn bạn đã quan tâm. Đội ngũ của chúng tôi sẽ liên hệ trong vòng 24 giờ.',
    sponsors_form_name: 'Họ và tên',
    sponsors_form_name_ph: 'Nguyễn Văn A',
    sponsors_form_company: 'Công ty / Tổ chức (Tùy chọn)',
    sponsors_form_company_ph: 'Acme Corp / Nhà tài trợ cá nhân',
    sponsors_form_email: 'Email',
    sponsors_form_email_ph: 'partner@company.com',
    sponsors_form_interest: 'Nội dung quan tâm',
    sponsors_form_interest_ph: 'Chia sẻ với chúng tôi về sự quan tâm tài trợ và mức ngân sách dự kiến của bạn...',
    sponsors_form_submit: 'GỬI YÊU CẦU'
  }
};
