import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // 'en' or 'vi'

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'vi' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    nav_home: 'HOME',
    nav_timeline: 'TIMELINE',
    nav_register: 'REGISTER',
    hero_title: 'HAEVTHON',
    hero_subtitle: "A 48-hour high-intensity sprint for elite builders. Architect, prototype, and deploy autonomous Agentic systems that redefine the future of AI on the Aevum infrastructure.",
    hero_cta_register: 'Register Now',
    hero_cta_explore: 'Explore Tracks',
    innovation_badge: 'OUR IMPACT',
    innovation_title: 'Driving the Innovation Wave in Vietnam',
    innovation_desc: 'Vietnam is rapidly emerging as a global hub for AI development. Haevthon 2026 is designed to empower local talent to build world-class Agentic Solutions.',
    innovation_highlight1_title: 'Catalyzing Growth',
    innovation_highlight1_desc: 'Hackathons are the engine of rapid prototyping, turning wild ideas into viable startups within 48 hours.',
    innovation_highlight2_title: "Vietnam's AI Era",
    innovation_highlight2_desc: 'With a booming tech ecosystem, Vietnam is rapidly becoming Southeast Asia\'s powerhouse for AI and automation.',
    innovation_highlight3_title: 'Building the Future',
    innovation_highlight3_desc: 'Haevthon is more than a competition; it\'s a movement to empower the next generation of Vietnamese builders.',
    innovation_stat1_label: 'AI Growth',
    innovation_stat1_desc: 'Annual growth in AI adoption',
    innovation_stat2_label: 'Startups',
    innovation_stat2_desc: 'New AI-driven tech startups',
    innovation_stat3_label: 'Talent',
    innovation_stat3_desc: 'Skilled developers joining the AI wave',
    tracks_title: 'CHALLENGE TRACKS',
    tracks_subtitle: 'Choose your path and build the future of Agentic Intelligence.',
    track1_title: 'AI Agents with Aevum',
    track1_desc: 'Build intelligent Agent systems and AI Workflows, optimizing autonomous operations.',
    track2_title: 'Workflow & Automation',
    track2_desc: 'Automate complex processes, creating powerful Ops and Internal Tools.',
    track3_title: 'Marketplace / Platform',
    track3_desc: 'Systems for connecting, trading, and coordinating services on the Aevum platform.',
    track4_title: 'Wildcard Innovation',
    track4_desc: 'Any breakthrough ideas using Aevum core infrastructure. Unlimited creativity.',
    track5_title: 'Data Intelligence',
    track5_desc: 'Build AI-powered analytics, data pipelines, and intelligent insights systems on top of Aevum.',
    track6_title: 'Open Source & Community',
    track6_desc: 'Create tools, SDKs, or frameworks that contribute back to the Aevum open-source ecosystem.',
    aevum_edge_title: 'THE AEVUM INFRASTRUCTURE',
    aevum_edge_subtitle: 'Build on the infrastructure that defines the future of AI Agent collaboration.',
    feature_squad_v2_title: 'Squad Mode v2.0',
    feature_squad_v2_desc: 'Professional handoffs, collaborative huddles, and synchronized squad-wide knowledge for multi-agent coordination.',
    feature_pipernet_ioa_title: 'PiperNet IoA',
    feature_pipernet_ioa_desc: 'Global IoA network connectivity with persona registration and community-wide collective intelligence queries.',
    feature_vibe_profiling_title: 'Vibe Profiling',
    feature_vibe_profiling_desc: 'Automated learning and persistence of unique user working styles, coding conventions, and architectural vibes.',
    feature_thought_stream_title: 'Proactive Thought Stream',
    feature_thought_stream_desc: 'Dedicated space for agent-initiated insights, warnings, and architectural thoughts without workflow interruption.',
    feature_memory_pulse_title: 'Memory Pulse (Self-Audit)',
    feature_memory_pulse_desc: 'Project memory health diagnostics and self-auditing to resolve knowledge conflicts and optimize token efficiency.',
    feature_vibe_space_title: 'Vibe Space',
    feature_vibe_space_desc: 'Distraction-free 3-column brainstorming workspace with real-time sync and cinematic onboarding flows.',
    feature_persona_evo_title: 'Persona Evolution',
    feature_persona_evo_desc: 'Living Skills Matrix and evolution history to track agent growth and capability resonance over project life.',
    feature_bridge_sse_title: 'Antigravity Bridge v2',
    feature_bridge_sse_desc: 'SSE-based server management and auto-discovery system for seamless IDE-to-Agent communication protocols.',
    aevum_intro_title: 'THE STORY OF AEVUM',
    aevum_intro_subtitle: 'Aevum is more than just technology; it is a journey that began with a core question within the Unikorn ecosystem: How can we stay focused in the explosion of the AI era? We have crafted a decentralized agentic protocol—a testament to Vietnamese engineering—that frees builders from the noise of complex workflows. It is a foundation where individual potential resonates into collective force, empowering you to orchestrate autonomous systems that learn and adapt, so we can redefine the future of innovation together.',
    aevum_story_ch1_title: 'THE GENESIS',
    aevum_story_ch1_desc: 'In the beginning, AI was a solitary spark. Powerful, yet isolated within the silos of single-user tasks and fragmented contexts.',
    aevum_story_ch2_title: 'THE EVOLUTION',
    aevum_story_ch2_desc: 'Aevum emerged as the bridge, a protocol designed to synchronize intent and action. It turned isolated tools into a living infrastructure.',
    aevum_story_ch3_title: 'THE RESONANCE',
    aevum_story_ch3_desc: 'Today, Aevum is the heart of the agentic swarm, where collective intelligence creates a resonance that defines the future of building.',
    aevum_story_ch4_title: 'LIVING MEMORY',
    aevum_story_ch4_desc: 'Aevum maintains high-fidelity project context across sessions, allowing agents to inherit architectural intent and ensure seamless continuity without redundant handovers.',
    aevum_intro_stat_title: 'SCALABILITY',
    aevum_intro_stat_desc: 'Architected for swarms of 100+ autonomous agents working in parallel.',
    aevum_intro_quote_title: 'LIVING MEMORY',
    aevum_intro_quote_desc: 'Aevum maintains project context with high-precision memory, allowing agents to inherit architectural intent across sessions.',
    aevum_intro_tech_title: 'PROTOCOL',
    aevum_intro_tech_desc: 'Low-latency event-driven architecture with sub-10ms resonance.',
    evolution_title: 'AEVUM EVOLUTION',
    evolution_subtitle: 'A transparent look into the rapid protocol growth and architectural milestones of the Aevum ecosystem.',
    evo_1_5_title: 'v1.5.0 - Squad Mode v2.0',
    evo_1_5_desc: 'Breakthrough in multi-agent coordination with professional handoffs, collective huddles, and PiperNet IoA integration.',
    evo_1_4_title: 'v1.4.0 - MCP-First Handshake',
    evo_1_4_desc: 'Core protocol evolution mandating MCP-based acknowledgments and lean signal systems for project-agent synchronization.',
    evo_1_3_title: 'v1.3.0 - Vibe Space UI',
    evo_1_3_desc: 'Browser-first brainstorming workspace with a minimalist 3-column layout and interactive session progress tracking.',
    evo_1_2_title: 'v1.2.0 - Collaborative Review',
    evo_1_2_desc: 'Centralized discussion space for Human-AI co-building, featuring thread awareness and automated self-reporting.',
    evo_learn_more: 'VIEW FULL CHANGELOG',
    video_badge: 'TECHNICAL GUIDE',
    video_title: 'AEVUM PROTOCOL GUIDE',
    video_subtitle: 'Master the core infrastructure. Learn how to initialize, configure, and orchestrate your agentic workspace with Aevum.',
    testimonial_title: 'Community Resonance',
    testimonial1_quote: 'The most thoughtfully designed agentic infrastructure I have ever used. Sleek, reliable, and truly innovative.',
    testimonial1_author: 'Senior AI Architect',
    testimonial2_quote: 'Squad Mode changed everything. The level of collaboration between agents feels like magic.',
    testimonial2_author: 'Full-stack Builder',
    testimonial3_quote: 'PiperNet integration is a game changer for distributed teams. The speed of coordination is unmatched.',
    testimonial3_author: 'Team Lead @ DevScale',
    testimonial4_quote: "Aevum's Living Memory is the missing piece for truly autonomous AI collaboration.",
    testimonial4_author: 'Open-source Contributor',
    vision_title: 'OUR MISSION',
    vision_desc: 'Haevthon is not just a coding competition, it is a **Product Factory**. We look for true Builders capable of turning ideas into working MVPs in hours.',
    vision_p1_title: 'Builder-first',
    vision_p1_desc: "We don't judge 'good ideas'. We judge buildability and execution.",
    vision_p2_title: 'Product-first',
    vision_p2_desc: 'Every team must aim for a real product with clear User Flow.',
    vision_p3_title: 'Tool-centric',
    vision_p3_desc: 'Aevum is the default infrastructure. Optimizing Aevum brings scoring advantages.',
    vision_scoring_title: 'SCORING FRAMEWORK',
    incentives_title: 'GRAND PRIZES',
    incentives_subtitle: 'Recognition and rewards for world-class innovation',
    tab_main_prizes: 'Main Prizes',
    tab_tech_awards: 'Technical',
    tab_team_awards: 'Team Awards',
    tab_impact_awards: 'Social Impact',
    tab_special_awards: 'Special',
    tab_community_awards: 'Community',
    incentive1_title: 'THE CHAMPION',
    incentive1_desc: 'The Final Boss. Built an MVP so smooth it made the judges cry (tears of joy, hopefully).',
    incentive2_title: 'ELITE BUILDER',
    incentive2_desc: 'Typing faster than their ex moved on. Craftsmanship that makes senior devs look twice.',
    incentive3_title: 'INNOVATION STAR',
    incentive3_desc: 'Idea so wild it might actually work. Built a prototype while everyone else was still brainstorming.',
    incentive4_title: 'AGENTIC ORCHESTRATOR',
    incentive4_desc: 'Managing agents like a pro circus director. No agent was harmed in the making of this project.',
    incentive5_title: 'HUMAN-CENTRIC DESIGN',
    incentive5_desc: 'UI so clean you could eat off it. Making complex AI look like a walk in the park.',
    incentive6_title: 'GHOST IN THE SHELL',
    incentive6_desc: 'Backend so solid even the hackers are asking for an internship. Scale? We eat scale for breakfast.',
    incentive7_title: 'PIPERNET RESONANCE',
    incentive7_desc: 'The system\'s "social butterfly". Shared more knowledge than a senior on Stack Overflow.',
    incentive8_title: 'ZERO-LATENCY GENIUS',
    incentive8_desc: 'Code runs faster than salary disappears on payday. Optimized to the atomic level.',
    incentive9_title: 'THE CATALYST',
    incentive9_desc: 'Solving real-world pain points faster than solving... instant noodles at 3 AM.',
    incentive10_title: 'SYNERGY SQUAD',
    incentive10_desc: 'Working together like a well-oiled machine (or a team of fishmongers at peak season).',
    incentive11_title: 'UNDERDOG CREW',
    incentive11_desc: 'Two people, 20-person output. Proving that size doesn\'t matter, but code quality does.',
    incentive12_title: 'DREAM TEAM',
    incentive12_desc: 'The Holy Trinity: Dev, Design, and Product. No merge conflicts can stop them.',
    incentive13_title: 'SOCIAL ARCHITECT',
    incentive13_desc: 'Using AI to actually help humanity instead of just... writing their homework.',
    incentive14_title: 'GREEN AGENT',
    incentive14_desc: 'Code so energy-efficient even Mother Nature wants to give you a high-five.',
    incentive15_title: 'ETHICAL GUARDIAN',
    incentive15_desc: 'The AI Police. Keeping things transparent, safe, and definitely not taking over the world.',
    incentive16_title: 'COFFEE ADDICT',
    incentive16_desc: 'Turned caffeine into code at an alarming rate. Most cups per capita.',
    incentive17_title: 'BUG MAGNET',
    incentive17_desc: 'Discovered the most "creative" bugs in Aevum. We are not even mad, that\'s amazing.',
    incentive18_title: 'THE PHOENIX',
    incentive18_desc: 'Rose from the ashes after a total system crash 10 minutes before demo.',
    incentive19_title: 'TECH EVANGELIST',
    incentive19_desc: 'Documentation so good it could be a best-selling novel. Sharing is caring!',
    incentive20_title: 'MARKET READY',
    incentive20_desc: 'Venture Capitalists are already calling. Most commercially viable MVP.',
    incentive21_title: 'THE ARCHITECT',
    incentive21_desc: 'System design so beautiful it belongs in a museum. Clean code is an understatement.',
    incentive22_title: 'SECURITY SENTINEL',
    incentive22_desc: 'Locked down tighter than a high-security vault. Paranoia is a feature here.',
    incentive23_title: 'DATA WHISPERER',
    incentive23_desc: 'Taming wild datasets like a pro. AI training so efficient it\'s scary.',
    incentive24_title: 'API NINJA',
    incentive24_desc: 'Integrating APIs faster than you can say "JSON". Silent but deadly efficient.',
    incentive25_title: 'GLOBAL SYNERGY',
    incentive25_desc: 'Collaboration that transcends borders. Time zones? We don\'t know them.',
    incentive26_title: 'MENTOR FAVORITE',
    incentive26_desc: 'The "Teacher\'s Pet" of the hackathon. Listened to every single piece of advice.',
    incentive27_title: 'SPEED DEMONS',
    incentive27_desc: 'First to submit. Did you even sleep? Or are you actually an AI?',
    incentive28_title: 'EDU-AGENT',
    incentive28_desc: 'Teaching the world one agent at a time. Education, but make it autonomous.',
    incentive29_title: 'HEALTH HERO',
    incentive29_desc: 'AI that cares. Solving health problems while we all survive on energy drinks.',
    incentive30_title: 'FINANCIAL INCLUSION',
    incentive30_desc: 'Bridging the wealth gap with smart agents. Robin Hood would be proud.',
    incentive31_title: 'FAN FAVORITE',
    incentive31_desc: 'The people have spoken. Most popular project in the room.',
    incentive32_title: 'SOCIAL STAR',
    incentive32_desc: 'Trending on Twitter before the demo even started. Viral by design.',
    incentive33_title: 'KINDNESS KING',
    incentive33_desc: 'Helped other teams fix their bugs. True sportsmanship at its finest.',
    incentive34_title: 'PIXEL PERFECT',
    incentive34_desc: 'UI so pretty it makes the designers cry. Every pixel in its rightful place.',
    incentive35_title: 'THE SURVIVOR',
    incentive35_desc: 'Still standing after 48 hours. Most likely to be a zombie by Monday.',
    incentive36_title: 'MERGE SURVIVOR',
    incentive36_desc: 'Survived a 50-file merge conflict without losing their mind. Heroic effort.',
    cta_compete_title: 'READY TO COMPETE?',
    cta_compete_desc: 'Limited spots available to ensure mentor quality and technical support.',
    cta_apply_now: 'Apply Now',
    partners_title: 'STRATEGIC PARTNERS',
    innovation_stats_believe: 'Of Vietnam\'s Top Tech Talents Believe AI is the Future.',
    innovation_effect_title: 'THE HACKATHON EFFECT',
    innovation_effect_desc: 'Statistics show that participants of intensive hackathons are 4x more likely to secure leadership roles in tech startups within 12 months of the event.',
    innovation_vision_cta: 'Learn About Our Vision',
    timeline_nav_hero: 'Start',
    timeline_nav_about: 'Vision',
    timeline_nav_features: 'Aevum Evo',
    timeline_nav_innovation: 'Logic',
    timeline_nav_vision: 'Principles',
    timeline_nav_tracks: 'Tracks',
    timeline_nav_incentives: 'Rewards',
    timeline_page_title: 'Event Journey',
    timeline_page_subtitle: 'Follow the path of innovation',
    timeline_phase0_title: 'Phase 0: Pre-Hackathon',
    timeline_phase0_desc: 'Early bird registration and technical readiness. Join our community and prepare your environment for the challenge ahead.',
    timeline_phase0_date: '7–14 days before',
    timeline_phase0_location: 'Online / Aevum PiperNet',
    timeline_phase0_items: [
      { time: '08:00 AM', title: 'Registration Open', detail: 'Secure your spot in the premier agentic hackathon. Limited seats available for elite builders.', status: 'active' },
      { time: '10:00 AM', title: 'FAQ & Support Window', detail: 'Continuous Q&A channel for technical inquiries, rule clarifications, and pre-event guidance.', status: 'upcoming' },
      { time: '02:00 PM', title: 'Meetup & Rules Briefing', detail: 'Virtual orientation to walk through the technical rules, scoring matrix, and Aevum integration requirements.', status: 'upcoming' },
      { time: '04:00 PM', title: 'Workshop: Aevum Onboarding', detail: 'Deep dive into the Aevum Core API, Squad Mode orchestration, and local environment setup.', status: 'upcoming' },
      { time: '06:00 PM', title: 'Team Formation matching', detail: 'Individual matching support for devs, designers, and product thinkers to find their perfect crew.', status: 'upcoming' }
    ],
    timeline_phase1_title: 'Phase 1: Kickoff',
    timeline_phase1_desc: 'The official start of Haevthon. Team formations are finalized and the core challenges are revealed by our mentors.',
    timeline_phase1_date: 'Day 0',
    timeline_phase1_location: 'Main Stage @ Innovation Hub',
    timeline_phase1_items: [
      { time: '09:00 AM', title: 'Opening Ceremony', detail: 'Keynote from I2FLabs architects and the reveal of the 2026 grand theme.', status: 'upcoming' },
      { time: '10:00 AM', title: 'Aevum Ecosystem Intro', detail: 'Overview of Aevum as a core build infrastructure and introduction to the dev squad.', isSpecial: true, status: 'upcoming' },
      { time: '10:30 AM', title: 'Problem Reveal', detail: 'Detailed briefing on the core challenges and edge cases you need to solve.', status: 'upcoming' },
      { time: '11:30 AM', title: 'Project Initialization', detail: 'Defining solution direction and phasc-ing out the initial MVP architecture.', status: 'upcoming' }
    ],
    timeline_phase2_title: 'Phase 2: Build Sprint',
    timeline_phase2_desc: 'Intensive 48-hour development cycle. Focus on architecting your agentic systems with the Aevum infrastructure.',
    timeline_phase2_date: '24–48 Hours',
    timeline_phase2_location: 'Hacker Den / Remote',
    timeline_phase2_items: [
      { time: '12:00 PM', title: 'Build Start', detail: 'The 48-hour sprint begins. Live technical support and mentor huddles are active.', status: 'upcoming' },
      { time: '04:00 PM', title: 'Energy Buff Session', detail: 'High-energy boost talks and rapid feedback to keep the momentum during the first 6 hours.', isSpecial: true, status: 'upcoming' },
      { time: '08:00 PM', title: 'Checkpoint Support Loop', detail: 'Mandatory technical check-ins to ensure your agentic flow is stable and scaling correctly.', status: 'upcoming' },
      { time: '11:00 PM', title: 'Builder Energy Talk', detail: 'Lightning talks from mentor guests on avoiding over-engineering and using Aevum for speed.', isSpecial: true, status: 'upcoming' }
    ],
    timeline_phase3_title: 'Phase 3: Demo Day',
    timeline_phase3_desc: 'Final showdown. Present your product to the panel of judges and the global community for scoring and awards.',
    timeline_phase3_date: 'Final Day',
    timeline_phase3_location: 'Grand Ballroom @ Tech City',
    timeline_phase3_items: [
      { time: '09:00 AM', title: 'Demo Presentations', detail: 'Live demonstration of your working MVP. 5 minutes per team followed by Q&A.', status: 'upcoming' },
      { time: '11:00 AM', title: 'Judge Feedback Loop', detail: 'Deep dive discussions with judges on product viability and architecture quality.', isSpecial: true, status: 'upcoming' },
      { time: '02:00 PM', title: 'Real-time Scoring', detail: 'Judges evaluation using the Aevum resonance and product viability metrics.', status: 'upcoming' },
      { time: '04:00 PM', title: 'Final Review', detail: 'Final consensus from the judging panel on the technical merit and innovation impact.', status: 'upcoming' }
    ],
    timeline_phase4_title: 'Phase 4: Awards & Beyond',
    timeline_phase4_desc: 'The journey continues. Final awards announcement, product incubation opportunities, and community integration for the winning agentic solutions.',
    timeline_phase4_date: 'Event Completion',
    timeline_phase4_location: 'Grand Ballroom & Digital Twin',
    timeline_phase4_items: [
      { time: '06:00 PM', title: 'Closing Ceremony', detail: 'Formal wrap-up of the event, key takeaways, and a glimpse into the future of the Aevum roadmap.', status: 'upcoming' },
      { time: '07:30 PM', title: 'Awards Announcement', detail: 'Recognition of the top builders, community choice awards, and distribution of the prize pool.', isSpecial: true, status: 'upcoming' },
      { time: '09:00 PM', title: 'Incubation Handshake', detail: 'Direct connection with investors and accelerators for post-hackathon scaling.', status: 'upcoming' }
    ],
    timeline_phase5_title: 'Phase 5: Community Choice',
    timeline_phase5_desc: 'The journey extends to the global community. Projects continue to participate in voting on the Unikorn platform for a chance to win exclusive ecosystem rewards.',
    timeline_phase5_date: 'Post-Event',
    timeline_phase5_location: 'Unikorn Platform',
    timeline_phase5_items: [
      { time: 'Week 1-2', title: 'Unikorn Voting Sprint', detail: 'Public voting period on Unikorn. Top projects receive additional community-driven funding and ecosystem perks.', isSpecial: true },
      { time: 'Monthly', title: 'Builder Updates', detail: 'Ongoing support and milestone tracking for projects transitioning into full-scale startups.' }
    ],
    reg_title: 'Join',
    reg_subtitle: 'Register to become a true Builder.',
    reg_label_name: 'Full Name',
    reg_placeholder_name: 'John Doe',
    reg_label_email: 'Email',
    reg_placeholder_email: 'john@example.com',
    reg_label_role: 'Role',
    reg_placeholder_role: 'Select...',
    reg_label_experience: 'Experience',
    reg_placeholder_experience: 'Select...',
    reg_label_interest: 'Project Direction',
    reg_placeholder_interest: 'Briefly share your ideas or skills...',
    reg_btn_submit: 'Confirm Registration',
    reg_btn_submitting: 'Submitting...',
    reg_success: 'Registration successful! Welcome to Haevthon. 🚀',
    reg_success_title: 'Application Received',
    reg_success_desc: 'Thank you for joining Haevthon. Our team will review your profile and contact you soon via email.',
    reg_btn_close: 'Close',
    reg_placeholder_select: 'Select...',
    reg_placeholder_select_answer: 'Select answer',
    reg_placeholder_select_source: 'Select source',
    reg_placeholder_select_goal: 'Select goal',
    reg_placeholder_select_status: 'Select status',
    reg_placeholder_select_role: 'Select role',
    reg_placeholder_select_level: 'Select level',
    reg_placeholder_select_country: 'Select country',
    reg_placeholder_select_city: 'Select city',
    err_name_min: 'Name must be at least 2 characters',
    err_email_invalid: 'Invalid email address',
    err_role_required: 'Role is required',
    err_experience_required: 'Experience is required',
    err_interest_min: 'Please describe your direction in more detail (at least 10 characters)',
    err_discord_required: 'Discord ID is required',
    err_linkedin_invalid: 'Invalid LinkedIn URL',
    err_github_invalid: 'Invalid Github/Portfolio URL',
    err_facebook_invalid: 'Invalid Facebook URL',
    err_team_required: 'Team name is required',
    err_skills_required: 'Skills are required',
    err_age_numeric: 'Age must be a number',
    reg_discord_label: 'DISCORD ID',
    reg_discord_ph: 'username#1234',
    reg_age_label: 'AGE',
    reg_gender_label: 'GENDER',
    reg_gender_male: 'Male',
    reg_gender_female: 'Female',
    reg_gender_other: 'Other',
    reg_linkedin_label: 'LINKEDIN URL (OPTIONAL)',
    reg_github_label: 'GITHUB / PORTFOLIO',
    reg_facebook_label: 'FACEBOOK URL (OPTIONAL)',
    reg_country_label: 'COUNTRY',
    reg_city_label: 'PROVINCE / CITY',
    reg_location_label: 'ACADEMIC OR WORK UNIT (IF ANY)',
    reg_placeholder_residence: 'University / Company...',
    reg_exp_student_hs: 'Student (High School)',
    reg_exp_student_uni: 'Student (University)',
    reg_exp_fresher: 'Fresher / New Grad',
    reg_exp_junior: 'Junior (1-2 years)',
    reg_exp_mid: 'Mid-level (3-5 years)',
    reg_exp_senior: 'Senior (5+ years)',
    reg_exp_expert: 'Lead / Expert',
    reg_role_ai: 'AI Engineer',
    reg_role_fullstack: 'Fullstack Developer',
    reg_role_designer: 'Product Designer',
    reg_role_manager: 'Product Manager',
    reg_survey_title: 'PRE-REGISTRATION SURVEY',
    reg_survey_subtitle: 'Please answer a few quick questions to help us prepare.',
    reg_survey_q1: 'Have you participated in a hackathon before?',
    reg_survey_q1_yes: 'Yes, I have',
    reg_survey_q1_no: "No, this is my first time",
    reg_survey_q2: 'How did you hear about Haevthon?',
    reg_survey_q2_social: 'Social Media',
    reg_survey_q2_friend: 'Friend / Colleague',
    reg_survey_q2_community: 'Tech Community / Club',
    reg_survey_q2_other: 'Other',
    reg_survey_q3: 'What is your primary goal for joining?',
    reg_survey_q3_learn: 'Learn & Build',
    reg_survey_q3_net: 'Networking',
    reg_survey_q3_prize: 'Win Prizes',
    reg_survey_q3_job: 'Career Opportunities',
    reg_survey_q4_label: 'ARE YOU LOOKING FOR A TEAM?',
    reg_survey_q4_yes: 'Yes, looking for teammates',
    reg_survey_q4_no: 'No, I already have a team',
    reg_survey_q4_solo: 'I want to compete solo',
    reg_survey_q5_label: 'WHAT IS YOUR PRIMARY ROLE?',
    reg_survey_q5_dev: 'Developer (Fullstack/FE/BE)',
    reg_survey_q5_ai: 'AI / ML Engineer',
    reg_survey_q5_design: 'UI/UX Designer',
    reg_survey_q5_biz: 'Product / Business / Hustler',
    reg_survey_q8_label: 'PREFERRED TECH / AI TOOLS',
    reg_survey_q9_label: 'ARE YOU READY FOR VIBECODING?',
    reg_survey_q9_new: 'What is Vibe coding?',
    reg_survey_q9_exploring: 'Exploring the vibes',
    reg_survey_q9_coder: 'Vibe Coder',
    reg_survey_q9_master: 'Master of Vibes',
    reg_survey_q10_label: 'YOUR AEVUMMAS SPIRIT LEVEL?',
    reg_survey_q10_new: 'Just discovered Aevum',
    reg_survey_q10_fan: 'Follower / Fan',
    reg_survey_q10_true: 'True Aevummas',
    reg_btn_next: 'NEXT STEP',
    reg_btn_back_survey: 'BACK TO SURVEY',
    reg_skills_label: 'SKILLS / TECH STACK',
    reg_team_label: 'TEAM NAME / PROJECT',
    reg_bio_label: 'PROJECT DIRECTION / BIO',
    reg_type_individual: 'INDIVIDUAL',
    reg_type_team: 'TEAM REGISTRATION',
    powered_by: 'Powered By Aevum',
    stats_prizepool: 'Prize Pool',
    stats_format: 'Format',
    stats_timeline: 'Timeline',
    stats_format_val: 'Online',
    stats_timeline_val: 'Coming Soon',
    status_upcoming: 'Upcoming',
    status_active: 'Live',
    status_done: 'Completed',
    nav_sponsors: 'SPONSORS',
    sponsors_partnership_opp: 'PARTNERSHIP OPPORTUNITY',
    sponsors_hero_title1: 'POWER THE',
    sponsors_hero_title2: 'AGENTIC',
    sponsors_hero_title3: 'REVOLUTION',
    sponsors_hero_desc: 'Haevthon 2026 is where the next generation of autonomous AI systems are born. Partner with us and position yourself or your brand at the frontier of agentic intelligence.',
    sponsors_hero_btn: 'BECOME A SPONSOR',
    sponsors_hosted_by: 'HOSTED BY',
    sponsors_org_committee: 'ORGANIZING COMMITTEE',
    sponsors_obj_title: 'OUR SHARED VISION',
    sponsors_obj_heading: 'SHAPING THE FUTURE',
    sponsors_obj_desc: 'Haevthon 2026 is more than a hackathon; it is a strategic launchpad. We are looking for partners who share our vision to push the boundaries of autonomous AI. Together, we provide the resources, platform, and mentorship needed to turn ambitious concepts into reality.',
    sponsors_obj_list1_title: 'Shape the Technology',
    sponsors_obj_list1_desc: 'Collaborate to establish new standards and frameworks for Agentic AI systems.',
    sponsors_obj_list2_title: 'Nurture Talent',
    sponsors_obj_list2_desc: 'Gain direct access to and support a curated network of elite engineers and researchers.',
    sponsors_obj_list3_title: 'Accelerate Innovation',
    sponsors_obj_list3_desc: 'Help turn breakthrough ideas into production-ready products immediately.',
    sponsors_unikorn_desc: 'Strategic Partner. Empowering the next generation of builders.',
    sponsors_i2flabs_desc: 'Primary Organizer & Innovation Hub. Driving the future of agentic technologies.',
    sponsors_aevum_desc: 'Co-Host & Technology Partner. The underlying foundation for autonomous AI systems.',
    sponsors_stats_title: 'BY THE NUMBERS',
    sponsors_why_title: 'WHY PARTNER WITH US',
    sponsors_why_label1: 'Elite Builders',
    sponsors_why_desc1: 'Top developers, designers, and AI researchers in one room.',
    sponsors_why_label2: 'Prize Pool',
    sponsors_why_desc2: 'Serious competitors building production-ready agentic products.',
    sponsors_why_label3: 'Build Sprint',
    sponsors_why_desc3: 'Intense format generating real, working MVPs — not just pitches.',
    sponsors_why_label4: 'Agentic Focus',
    sponsors_why_desc4: 'The most specialized AI hackathon in Southeast Asia.',
    sponsors_contact_title: 'GET IN TOUCH',
    sponsors_contact_heading1: 'LET\'S BUILD',
    sponsors_contact_heading2: 'TOGETHER',
    sponsors_contact_desc: 'Interested in sponsoring Haevthon 2026? Reach out and our partnership team will connect with you within 24 hours to discuss the best package for you or your organization.',
    sponsors_form_success_title: 'Inquiry Received',
    sponsors_form_success_desc: 'Thank you for your interest. Our team will reach out within 24 hours.',
    sponsors_form_name: 'Your Name',
    sponsors_form_name_ph: 'Nguyen Van A',
    sponsors_form_company: 'Company / Organization (Optional)',
    sponsors_form_company_ph: 'Acme Corp / Individual Sponsor',
    sponsors_form_email: 'Email',
    sponsors_form_email_ph: 'partner@company.com',
    sponsors_form_interest: 'Partnership Interest',
    sponsors_form_interest_ph: 'Share with us about your sponsorship interest and estimated budget...',
    sponsors_form_submit: 'SEND INQUIRY',
    contact_email: 'hainguyen0112358@gmail.com',
    contact_phone: '+84 (0) 879 29 9627',
    contact_address: 'Ho Chi Minh City, Vietnam',
    contact_website: 'i2flabs.unikorn.vn',
    powered_by_prefix: 'POWERED BY',
    about_badge: 'THE VISION',
    about_title_part1: 'HAEVTHON',
    about_title_part2: 'ARCHITECTING',
    about_title_part3: 'AUTONOMY',
    about_desc: "Haevthon is the world's premier arena for Advanced Agentic Systems. We don't just build code; we orchestrate intelligence. Our mission is to empower the next generation of builders to move beyond static automation into the realm of truly autonomous agentic swarms.",
    about_core_title: 'AGENTIC CORE',
    about_core_desc: 'Building the foundational logic for autonomous AI agents that can think and act.',
    about_swarm_title: 'SWARM INTELLIGENCE',
    about_swarm_desc: 'Exploring multi-agent collaboration where agents solve complex tasks together.',
    about_cta: 'LEARN MORE ABOUT OUR MISSION',
    about_card_title: 'HAEVTHON 2026',
    about_card_desc: 'The definitive destination for pioneering agentic builders worldwide.',
    innovation_title_part1: 'DRIVING THE',
    innovation_title_part2: 'INNOVATION',
    innovation_title_part3: 'WAVE',
    innovation_desc_main: 'Vietnam is rapidly emerging as a global hub for AI development. Haevthon is designed to empower local talent to build world-class Agentic Solutions that redefine autonomy.',
    innovation_item1_title: 'CATALYZING GROWTH',
    innovation_item1_desc: 'Hackathons are the engine of rapid prototyping, turning wild ideas into viable startups.',
    innovation_item2_title: "VIETNAM'S AI ERA",
    innovation_item2_desc: 'With a booming tech ecosystem, Vietnam is rapidly becoming Southeast Asia\'s powerhouse.',
    innovation_item3_title: 'BUILDING THE FUTURE',
    innovation_item3_desc: 'Haevthon is a movement to empower the next generation of global builders.',
    vision_score_exec: 'Execution',
    vision_score_product: 'Product Thinking',
    vision_score_util: 'Aevum Utilization',
    vision_score_innov: 'Innovation',
    footer_desc: 'Empowering the next generation of autonomous AI systems. Built by builders, for builders.',
    footer_explore: 'Explore',
    footer_connect: 'Connect',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_rights: 'All rights reserved.'
  },
  vi: {
    nav_home: 'TRANG CHỦ',
    nav_timeline: 'LỘ TRÌNH',
    nav_register: 'ĐĂNG KÝ',
    hero_title: 'HAEVTHON',
    hero_subtitle: "48 giờ xây dựng cường độ cao dành cho các Builder tinh hoa. Kiến tạo, thử nghiệm và triển khai các hệ thống AI Tác tử tự chủ, định hình lại tương lai trí tuệ nhân tạo trên nền tảng Aevum.",
    hero_cta_register: 'Đăng Ký Ngay',
    hero_cta_explore: 'Khám Phá Các Track',
    innovation_badge: 'TẦM ẢNH HƯỞNG',
    innovation_title: 'Thúc Đẩy Làn Sóng Đổi Mới Tại Việt Nam',
    innovation_desc: 'Việt Nam đang nhanh chóng trở thành trung tâm phát triển AI toàn cầu. Haevthon 2026 được thiết kế để tiếp sức cho tài năng Việt xây dựng các Giải pháp Tác tử đẳng cấp thế giới.',
    innovation_highlight1_title: 'Thúc Đẩy Tăng Trưởng',
    innovation_highlight1_desc: 'Hackathon là động cơ tạo mẫu nhanh, biến các ý tưởng táo bạo thành các startup tiềm năng chỉ trong 48 giờ.',
    innovation_highlight2_title: "Kỷ Nguyên AI Việt Nam",
    innovation_highlight2_desc: 'Với hệ sinh thái công nghệ đang bùng nổ, Việt Nam đang nhanh chóng trở thành cường quốc AI và tự động hóa tại Đông Nam Á.',
    innovation_highlight3_title: 'Xây Dựng Tương Lai',
    innovation_highlight3_desc: 'Haevthon không chỉ là một cuộc thi; đó là một phong trào để tiếp sức cho thế hệ những nhà xây dựng Việt Nam tiếp theo.',
    innovation_stat1_label: 'Tăng Trưởng AI',
    innovation_stat1_desc: 'Tăng trưởng ứng dụng AI hàng năm',
    innovation_stat2_label: 'Startup',
    innovation_stat2_desc: 'Các công ty khởi nghiệp AI mới',
    innovation_stat3_label: 'Nhân Tài',
    innovation_stat3_desc: 'Lập trình viên tài năng gia nhập làn sóng AI',
    tracks_title: 'CÁC LĨNH VỰC THỬ THÁCH',
    tracks_subtitle: 'Chọn con đường của bạn và xây dựng tương lai của Trí tuệ Tác tử.',
    track1_title: 'Tác Tử AI với Aevum',
    track1_desc: 'Xây dựng hệ thống Agent và AI Workflow thông minh, tối ưu hóa khả năng tự vận hành.',
    track2_title: 'Quy Trình & Tự Động Hóa',
    track2_desc: 'Tự động hóa các quy trình phức tạp, tạo ra các công cụ Ops và Internal Tools mạnh mẽ.',
    track3_title: 'Nền Tảng / Chợ Ứng Dụng',
    track3_desc: 'Hệ thống kết nối, giao dịch và điều phối dịch vụ trên nền tảng Aevum.',
    track4_title: 'Sáng Tạo Đột Phá',
    track4_desc: 'Mọi ý tưởng đột phá sử dụng lõi hạ tầng Aevum. Không giới hạn sự sáng tạo.',
    track5_title: 'Dữ Liệu Thông Minh',
    track5_desc: 'Xây dựng hệ thống phân tích AI, data pipeline và insights thông minh trên nền tảng Aevum.',
    track6_title: 'Nguồn Mở & Cộng Đồng',
    track6_desc: 'Tạo ra các công cụ, SDK hoặc framework đóng góp vào hệ sinh thái mã nguồn mở của Aevum.',
    aevum_edge_title: 'HẠ TẦNG AEVUM',
    aevum_edge_subtitle: 'Xây dựng trên nền tảng hạ tầng định hình tương lai của sự cộng tác giữa các Tác tử AI.',
    feature_squad_v2_title: 'Squad Mode v2.0',
    feature_squad_v2_desc: 'Bàn giao công việc chuyên nghiệp, hội ý nhóm và đồng bộ tri thức toàn đội ngũ đa tác tử.',
    feature_pipernet_ioa_title: 'PiperNet IoA',
    feature_pipernet_ioa_desc: 'Kết nối mạng lưới IoA toàn cầu, hỗ trợ đăng ký định danh và truy vấn trí tuệ tập thể từ cộng đồng.',
    feature_vibe_profiling_title: 'Vibe Profiling',
    feature_vibe_profiling_desc: 'Tự động học hỏi và lưu trữ phong cách làm việc, quy chuẩn code và "vibe" kiến trúc riêng biệt của bạn.',
    feature_thought_stream_title: 'Luồng Tư duy Chủ động',
    feature_thought_stream_desc: 'Không gian riêng cho các thông tin chuyên sâu và cảnh báo do tác tử tự khởi xướng mà không làm gián đoạn luồng việc.',
    feature_memory_pulse_title: 'Memory Pulse (Tự kiểm toán)',
    feature_memory_pulse_desc: 'Chẩn đoán sức khỏe bộ nhớ dự án và tự kiểm toán để giải quyết xung đột tri thức và tối ưu hóa hiệu suất.',
    feature_vibe_space_title: 'Vibe Space',
    feature_vibe_space_desc: 'Không gian làm việc 3 cột chuyên sâu cho ý tưởng, đồng bộ thời gian thực với trải nghiệm điện ảnh.',
    feature_persona_evo_title: 'Tiến hóa Persona',
    feature_persona_evo_desc: 'Ma trận kỹ năng sống và lịch sử tiến hóa giúp theo dõi sự trưởng thành và cộng hưởng năng lực của tác tử.',
    feature_bridge_sse_title: 'Cầu nối Antigravity v2',
    feature_bridge_sse_desc: 'Quản lý máy chủ dựa trên SSE và hệ thống tự động khám phá giúp tối ưu giao thức truyền thông IDE-Tác tử.',
    aevum_intro_title: 'CÂU CHUYỆN VỀ AEVUM',
    aevum_intro_subtitle: 'Aevum không chỉ là công nghệ, mà là một hành trình bắt đầu từ những trăn trở tại hệ sinh thái Unikorn: Làm sao để con người không bị lạc lối giữa kỷ nguyên AI bùng nổ? Chúng tôi đã cùng nhau kiến tạo nên một giao thức tác tử phi tập trung - niềm tự hào của trí tuệ Việt, giúp các nhà kiến tạo giải phóng sức sáng tạo khỏi những quy trình phức tạp. Đây là nơi tiềm năng cá nhân cộng hưởng thành sức mạnh tập thể, giúp bạn điều phối những hệ thống tự chủ biết học hỏi và thích nghi, để cùng nhau định nghĩa lại tương lai của sự đổi mới.',
    aevum_story_ch1_title: 'KHỞI NGUYÊN',
    aevum_story_ch1_desc: 'Thuở ban đầu, AI chỉ là một tia sáng đơn lẻ. Mạnh mẽ nhưng bị cô lập trong những tác vụ đơn người và những bối cảnh phân mảnh.',
    aevum_story_ch2_title: 'TIẾN HÓA',
    aevum_story_ch2_desc: 'Aevum xuất hiện như một nhịp cầu, một giao thức được thiết kế để đồng bộ hóa ý định và hành động. Nó biến những công cụ rời rạc thành một hạ tầng sống động.',
    aevum_story_ch3_title: 'CỘNG HƯỞNG',
    aevum_story_ch3_desc: 'Ngày nay, Aevum là trái tim của bầy đàn tác tử, nơi trí tuệ tập thể tạo ra sự cộng hưởng định nghĩa tương lai của việc kiến tạo.',
    aevum_story_ch4_title: 'BỘ NHỚ SỐNG',
    aevum_story_ch4_desc: 'Aevum duy trì bối cảnh dự án với độ chính xác cao xuyên suốt các phiên, cho phép tác tử kế thừa ý định kiến trúc và đảm bảo tính liên tục mà không cần bàn giao dư thừa.',
    aevum_intro_stat_title: 'KHẢ NĂNG MỞ RỘNG',
    aevum_intro_stat_desc: 'Được thiết kế cho các bầy đàn hơn 100 tác tử tự chủ làm việc song song.',
    aevum_intro_quote_title: 'BỘ NHỚ SỐNG',
    aevum_intro_quote_desc: 'Aevum duy trì bối cảnh dự án với trí nhớ độ chính xác cao, cho phép các tác tử kế thừa ý định kiến trúc xuyên suốt các phiên làm việc.',
    aevum_intro_tech_title: 'GIAO THỨC',
    aevum_intro_tech_desc: 'Kiến trúc hướng sự kiện với độ trễ cộng hưởng cực thấp dưới 10ms.',
    evolution_title: 'TIẾN HÓA AEVUM',
    evolution_subtitle: 'Cái nhìn minh bạch về sự phát triển thần tốc của các giao thức và cột mốc kiến trúc trong hệ sinh thái Aevum.',
    evo_1_5_title: 'v1.5.0 - Squad Mode v2.0',
    evo_1_5_desc: 'Bước đột phá trong điều phối đa tác tử với hệ thống bàn giao chuyên nghiệp, hội ý nhóm và tích hợp PiperNet IoA.',
    evo_1_4_title: 'v1.4.0 - Bắt tay MCP-First',
    evo_1_4_desc: 'Tiến hóa giao thức lõi, yêu cầu xác nhận dựa trên MCP và hệ thống tín hiệu tinh gọn để đồng bộ hóa dự án-tác tử.',
    evo_1_3_title: 'v1.3.0 - Giao diện Vibe Space',
    evo_1_3_desc: 'Không gian làm việc brainstorm ưu tiên trình duyệt với bố cục 3 cột tối giản và theo dõi tiến độ tương tác.',
    evo_1_2_title: 'v1.2.0 - Đánh giá Cộng tác',
    evo_1_2_desc: 'Không gian thảo luận tập trung cho sự đồng kiến tạo Người-AI, hỗ trợ nhận thức luồng chat và tự động báo cáo.',
    evo_learn_more: 'XEM ĐẦY ĐỦ CHANGELOG',
    video_badge: 'HƯỚNG DẪN KỸ THUẬT',
    video_title: 'CẨM NANG GIAO THỨC AEVUM',
    video_subtitle: 'Làm chủ hạ tầng cốt lõi. Tìm hiểu cách khởi tạo, cấu hình và điều phối không gian làm việc tác tử của bạn với Aevum.',
    testimonial_title: 'Tiếng Vang Cộng Đồng',
    testimonial1_quote: 'Hạ tầng tác tử được thiết kế tỉ mỉ nhất mà tôi từng sử dụng. Sang trọng, tin cậy và thực sự đột phá.',
    testimonial1_author: 'Kiến trúc sư AI Cao cấp',
    testimonial2_quote: 'Squad Mode đã thay đổi tất cả. Cấp độ cộng tác giữa các tác tử thực sự mang lại cảm giác như phép màu.',
    testimonial2_author: 'Nhà phát triển Full-stack',
    testimonial3_quote: 'Tích hợp PiperNet là một bước ngoặt cho các đội ngũ làm việc phân tán. Tốc độ điều phối thực sự vô đối.',
    testimonial3_author: 'Trưởng nhóm tại DevScale',
    testimonial4_quote: 'Bộ nhớ vĩnh cửu của Aevum là mảnh ghép còn thiếu cho sự cộng tác AI thực sự tự chủ.',
    testimonial4_author: 'Người đóng góp mã nguồn mở',
    vision_title: 'SỨ MỆNH CỦA CHÚNG TÔI',
    vision_desc: 'Haevthon không chỉ là một cuộc thi code, mà là một **Product Factory**. Chúng tôi tìm kiếm những Builder thực thụ có khả năng biến ý tưởng thành MVP chạy được chỉ trong vài giờ.',
    vision_p1_title: 'Ưu tiên Builder',
    vision_p1_desc: "Chúng tôi không chấm 'ý tưởng hay'. Chúng tôi chấm độ thực thi và vận hành thực tế.",
    vision_p2_title: 'Ưu tiên Sản phẩm',
    vision_p2_desc: 'Mọi đội thi phải hướng tới sản phẩm thực tế, có luồng người dùng (User Flow) rõ ràng.',
    vision_p3_title: 'Trọng tâm Công cụ',
    vision_p3_desc: 'Aevum là hạ tầng mặc định. Tối ưu hóa Aevum mang lại lợi thế về điểm số.',
    vision_scoring_title: 'KHUNG ĐIỂM ĐÁNH GIÁ',
    incentives_title: 'CƠ CẤU GIẢI THƯỞNG',
    incentives_subtitle: 'Phần thưởng xứng đáng cho những nhà kiến tạo tinh hoa',
    tab_main_prizes: 'Giải Thưởng Chính',
    tab_tech_awards: 'Kỹ Thuật',
    tab_team_awards: 'Đội Ngũ',
    tab_impact_awards: 'Nhân Văn',
    tab_special_awards: 'Đặc Biệt',
    tab_community_awards: 'Cộng Đồng',
    incentive1_title: 'QUÁN QUÂN',
    incentive1_desc: 'Trùm cuối Haevthon. Xây dựng được MVP mượt đến mức BGK tưởng đang xem phim sci-fi.',
    incentive2_title: 'BUILDER TINH HOA',
    incentive2_desc: 'Gõ phím nhanh hơn cách người cũ quay lưng. Kỹ năng "thợ xây" bậc thầy khiến ai cũng phải nể.',
    incentive3_title: 'NGÔI SAO SÁNG TẠO',
    incentive3_desc: 'Ý tưởng "ảo ma" đến mức BGK cũng phải dụi mắt, nhưng quan trọng là nó... CHẠY ĐƯỢC!',
    incentive4_title: 'BẬC THẦY ĐIỀU PHỐI',
    incentive4_desc: '"Chăn dắt" dàn Agents của Aevum điêu luyện như cách "Team bán cá" chốt đơn ngày Tết.',
    incentive5_title: 'THIẾT KẾ VÌ CON NGƯỜI',
    incentive5_desc: 'UI mượt đến mức người dùng tưởng mình đang ở năm 2077. Không tì vết, không "lỗi font".',
    incentive6_title: 'HỆ THỐNG TINH HOA',
    incentive6_desc: 'Backend cứng như kim cương. Bảo mật đến mức hacker cũng phải xin "job" làm cùng vì quá nể.',
    incentive7_title: 'CỘNG HƯỞNG PIPERNET',
    incentive7_desc: '"Bà hàng xóm" của hệ thống - biết tất cả, chia sẻ tất cả, không để bất kỳ AI nào bị bỏ lại phía sau.',
    incentive8_title: 'THIÊN TÀI TỐI ƯU',
    incentive8_desc: 'Code chạy nhanh hơn cách lương về rồi đi. Tối ưu đến từng micro-giây, không một động thái thừa.',
    incentive9_title: 'KẺ THÚC ĐẨY',
    incentive9_desc: 'Giải quyết nỗi đau của ngành nhanh hơn cách bạn giải quyết... bát mì tôm lúc 3h sáng đêm hackathon.',
    incentive10_title: 'BIỆT ĐỘI CỘNG HƯỞNG',
    incentive10_desc: 'Phối hợp ăn ý như "Team bán cá": người cân team, người cân... cá, kết quả cực cháy!',
    incentive11_title: 'CHIẾN BINH THẦM LẶNG',
    incentive11_desc: 'Team có 2 người nhưng code bằng 20 người. Chứng minh "nhỏ mà có võ" là định nghĩa của team này.',
    incentive12_title: 'ĐỘI NGŨ TRONG MƠ',
    incentive12_desc: 'Bộ ba "hủy diệt": Dev, Designer và Product. Hợp thể mạnh đến mức không một Merge Conflict nào cản nổi.',
    incentive13_title: 'KIẾN TRÚC SƯ XÃ HỘI',
    incentive13_desc: 'Dùng AI để thực sự giúp đỡ con người, thay vì chỉ dùng để... viết hộ bài luận cuối kỳ.',
    incentive14_title: 'TÁC TỬ XANH',
    incentive14_desc: 'Code tiết kiệm điện đến mức Mẹ Thiên Nhiên cũng phải gửi lời cảm ơn "Thank you, Next!".',
    incentive15_title: 'NGƯỜI GÁC ĐỀN ĐẠO ĐỨC',
    incentive15_desc: 'Những "cảnh sát" AI chính trực. Giữ cho hệ thống luôn minh bạch, an toàn và chắc chắn là không... chiếm lĩnh thế giới.',
    incentive16_title: 'CHIẾN THẦN CAFFEINE',
    incentive16_desc: 'Chuyển hóa cà phê thành code với tốc độ báo động. Team uống nhiều nhất giải.',
    incentive17_title: 'NAM CHÂM HÚT BUG',
    incentive17_desc: 'Tìm ra những chiếc bug "sáng tạo" nhất hệ thống Aevum. Không giận, chỉ thấy nể!',
    incentive18_title: 'PHƯỢNG HOÀNG LỬA',
    incentive18_desc: 'Hồi sinh thần kỳ sau một cú sập hệ thống toàn diện chỉ 10 phút trước giờ Demo.',
    incentive19_title: 'SỨ GIẢ CÔNG NGHỆ',
    incentive19_desc: 'Viết tài liệu hay đến mức có thể xuất bản thành tiểu thuyết. Chia sẻ là đam mê!',
    incentive20_title: 'SẴN SÀNG THỰC CHIẾN',
    incentive20_desc: 'Các quỹ đầu tư đang gọi cháy máy. MVP có tiềm năng thương mại hóa cao nhất.',
    incentive21_title: 'KIẾN TRÚC SƯ TRƯỞNG',
    incentive21_desc: 'Thiết kế hệ thống đẹp như tranh vẽ. Code sạch đến mức không nỡ commit.',
    incentive22_title: 'VỆ BINH BẢO MẬT',
    incentive22_desc: 'Khóa chặt hệ thống như kho bạc nhà nước. Bảo mật là ưu tiên số 1.',
    incentive23_title: 'PHÙ THỦY DỮ LIỆU',
    incentive23_desc: 'Thuần hóa những bộ dữ liệu khổng lồ. AI học nhanh đến mức đáng sợ.',
    incentive24_title: 'NINJA API',
    incentive24_desc: 'Kết nối API nhanh hơn cách bạn nói "JSON". Âm thầm nhưng cực kỳ hiệu quả.',
    incentive25_title: 'CỘNG HƯỞNG TOÀN CẦU',
    incentive25_desc: 'Phối hợp xuyên biên giới. Múi giờ? Chúng tôi không biết định nghĩa đó.',
    incentive26_title: 'HỌC TRÒ CƯNG MENTOR',
    incentive26_desc: '"Học bá" của Hackathon. Nghe và áp dụng mọi lời khuyên từ các chuyên gia.',
    incentive27_title: 'QUÁI VẬT TỐC ĐỘ',
    incentive27_desc: 'Nộp bài đầu tiên. Bạn có ngủ không? Hay bạn chính là một AI?',
    incentive28_title: 'TÁC TỬ GIÁO DỤC',
    incentive28_desc: 'Dạy cả thế giới bằng các Agents. Học tập chưa bao giờ tự động đến thế.',
    incentive29_title: 'NGƯỜI HÙNG SỨC KHỎE',
    incentive29_desc: 'Dùng AI để cứu người, trong khi chính mình đang "sống sót" nhờ nước tăng lực.',
    incentive30_title: 'TÀI CHÍNH TOÀN DÂN',
    incentive30_desc: 'Xóa bỏ khoảng cách giàu nghèo bằng Agents thông minh. Robin Hood thời đại số.',
    incentive31_title: 'GƯƠNG MẶT THÂN QUEN',
    incentive31_desc: 'Tiếng nói của nhân dân. Dự án được yêu thích nhất trong khán phòng.',
    incentive32_title: 'NGÔI SAO MẠNG XÃ HỘI',
    incentive32_desc: 'Trending trên Twitter trước cả khi kịp Demo. Viral là bản năng.',
    incentive33_title: 'SỨ GIẢ TỬ TẾ',
    incentive33_desc: 'Nhiệt tình sửa bug hộ team bạn. Tinh thần thể thao cao thượng nhất giải.',
    incentive34_title: 'ĐIỂM 10 THẨM MỸ',
    incentive34_desc: 'UI đẹp đến mức Designer phải rơi lệ. Từng pixel đều nằm đúng chỗ.',
    incentive35_title: 'CHIẾN BINH BẤT TỬ',
    incentive35_desc: 'Vẫn đứng vững sau 48 giờ. Dự kiến sẽ biến thành zombie vào sáng thứ Hai.',
    incentive36_title: 'KẺ SỐNG SÓT SAU MERGE',
    incentive36_desc: 'Vượt qua cú Merge 50 file mà không mất bình tĩnh. Nỗ lực phi thường.',
    cta_compete_title: 'BẠN ĐÃ SẴN SÀNG?',
    cta_compete_desc: 'Số lượng tham gia có hạn để đảm bảo chất lượng mentor và hỗ trợ kỹ thuật tốt nhất.',
    cta_apply_now: 'Đăng ký ngay',
    partners_title: 'ĐỐI TÁC CHIẾN LƯỢC',
    innovation_highlight1_title: 'Thúc Đẩy Tăng Trưởng',
    innovation_highlight1_desc: 'Hackathon là động cơ tạo mẫu nhanh, biến các ý tưởng táo bạo thành các startup tiềm năng chỉ trong 48 giờ.',
    innovation_highlight2_title: "Kỷ Nguyên AI Việt Nam",
    innovation_highlight2_desc: 'Với hệ sinh thái công nghệ đang bùng nổ, Việt Nam đang nhanh chóng trở thành cường quốc AI và tự động hóa tại Đông Nam Á.',
    innovation_highlight3_title: 'Xây Dựng Tương Lai',
    innovation_highlight3_desc: 'Haevthon không chỉ là một cuộc thi; đó là một phong trào để tiếp sức cho thế hệ những nhà xây dựng Việt Nam tiếp theo.',
    innovation_stats_believe: 'Nhân Tài Công Nghệ Việt Nam Tin Rằng AI Chính Là Tương Lai.',
    innovation_effect_title: 'HIỆU ỨNG HACKATHON',
    innovation_effect_desc: 'Thống kê cho thấy những người tham gia hackathon cường độ cao có khả năng đảm nhận các vai trò lãnh đạo tại các startup công nghệ cao gấp 4 lần trong vòng 12 tháng sau sự kiện.',
    innovation_vision_cta: 'Tìm Hiểu Về Tầm Nhìn',
    timeline_nav_hero: 'Khởi đầu',
    timeline_nav_about: 'Tầm nhìn',
    timeline_nav_features: 'Aevum Evo',
    timeline_nav_innovation: 'Lợi thế',
    timeline_nav_vision: 'Sứ mệnh',
    timeline_nav_tracks: 'Lĩnh vực',
    timeline_nav_incentives: 'Giải thưởng',
    timeline_page_title: 'Hành Trình Sự Kiện',
    timeline_page_subtitle: 'Theo dấu con đường của sự đổi mới',
    timeline_phase0_title: 'Giai Đoạn 0: Tiền Sự Kiện',
    timeline_phase0_desc: 'Giai đoạn đăng ký sớm và chuẩn bị kỹ thuật. Gia nhập cộng đồng và thiết lập môi trường để sẵn sàng cho thử thách.',
    timeline_phase0_date: '7–14 ngày trước',
    timeline_phase0_location: 'Trực tuyến / Aevum PiperNet',
    timeline_phase0_items: [
      { time: '08:00 SA', title: 'Mở cổng đăng ký', detail: 'Giành suất tham gia hackathon tác tử hàng đầu. Số lượng giới hạn cho các builder xuất sắc.', status: 'active' },
      { time: '10:00 SA', title: 'FAQ & Hỗ trợ kỹ thuật', detail: 'Kênh hỏi đáp liên tục để giải đáp thắc mắc về luật thi, kỹ thuật và định hướng sản phẩm.', status: 'upcoming' },
      { time: '02:00 CH', title: 'Meetup & Phổ biến luật thi', detail: 'Buổi định hướng trực tuyến để tìm hiểu về luật lệ kỹ thuật, khung điểm và yêu cầu tích hợp Aevum.', status: 'upcoming' },
      { time: '04:00 CH', title: 'Workshop: Đào tạo Aevum', detail: 'Đi sâu vào Aevum Core API, điều phối Squad Mode và thiết lập môi trường lập trình.', status: 'upcoming' },
      { time: '06:00 CH', title: 'Hỗ trợ ghép đội thi', detail: 'Hỗ trợ kết nối Dev, Designer và Product Owner để hình thành đội ngũ thiện chiến nhất.', status: 'upcoming' }
    ],
    timeline_phase1_title: 'Giai Đoạn 1: Khởi Động',
    timeline_phase1_desc: 'Khai mạc chính thức Haevthon. Chốt danh sách đội ngũ và công bố các bài toán hóc búa từ đội ngũ mentor.',
    timeline_phase1_date: 'Ngày 0',
    timeline_phase1_location: 'Sân khấu chính @ Innovation Hub',
    timeline_phase1_items: [
      { time: '09:00 SA', title: 'Lễ khai mạc', detail: 'Bài phát biểu từ các kiến trúc sư I2FLabs và công bố chủ đề lớn của năm 2026.' },
      { time: '10:00 SA', title: 'Giới thiệu Hệ sinh thái Aevum', detail: 'Cái nhìn tổng quan về Aevum như một hạ tầng build core và ra mắt đội ngũ hỗ trợ.', isSpecial: true },
      { time: '10:30 SA', title: 'Công bố đề bài', detail: 'Phổ biến chi tiết về các thử thách cốt lõi và các trường hợp biên bạn cần giải quyết.' },
      { time: '11:30 SA', title: 'Khởi tạo dự án Sprint', detail: 'Xác định hướng giải pháp và phác thảo kiến trúc MVP ban đầu.' }
    ],
    timeline_phase2_title: 'Giai Đoạn 2: Xây Dựng',
    timeline_phase2_desc: 'Chu kỳ phát triển 48 giờ cường độ cao. Tập trung thiết kế hệ thống tác tử trên nền tảng hạ tầng Aevum.',
    timeline_phase2_date: '24–48 Giờ',
    timeline_phase2_location: 'Khu vực Builder / Từ xa',
    timeline_phase2_items: [
      { time: '12:00 CH', title: 'Bắt đầu xây dựng', detail: 'Bắt đầu cuộc đua 48 giờ. Đội ngũ hỗ trợ kỹ thuật và mentor luôn sẵn sàng đồng hành.' },
      { time: '04:00 CH', title: 'Phiên Energy Buff', detail: 'Các buổi truyền lửa và phản hồi nhanh để giữ nhịp độ trong 6 giờ đầu tiên.', isSpecial: true },
      { time: '08:00 CH', title: 'Vòng lặp Checkpoint hỗ trợ', detail: 'Các buổi kiểm tra kỹ thuật bắt buộc để đảm bảo luồng tác tử của bạn ổn định và mở rộng đúng hướng.' },
      { time: '11:00 CH', title: 'Builder Energy Talk', detail: 'Chia sẻ từ các Mentor về cách tránh over-engineering và dùng Aevum để tăng tốc.', isSpecial: true }
    ],
    timeline_phase3_title: 'Giai Đoạn 3: Demo Day',
    timeline_phase3_desc: 'Vòng chung kết. Thuyết trình sản phẩm trước ban giám khảo và cộng đồng toàn cầu để nhận điểm và giải thưởng.',
    timeline_phase3_date: 'Ngày Cuối',
    timeline_phase3_location: 'Hội trường lớn @ Tech City',
    timeline_phase3_items: [
      { time: '09:00 SA', title: 'Thuyết trình Demo', detail: 'Trình diễn trực tiếp sản phẩm MVP. 5 phút cho mỗi đội kèm theo phần hỏi đáp.', status: 'upcoming' },
      { time: '11:00 SA', title: 'Vòng phản hồi từ BGK', detail: 'Thảo luận sâu với ban giám khảo về tính khả thi của sản phẩm và chất lượng kiến trúc.', isSpecial: true, status: 'upcoming' },
      { time: '02:00 CH', title: 'Chấm điểm thời gian thực', detail: 'Ban giám khảo đánh giá dựa trên tiêu chuẩn cộng hưởng Aevum và tính khả thi của sản phẩm.', status: 'upcoming' },
      { time: '04:00 CH', title: 'Đánh giá chung khảo', detail: 'Đội ngũ giám khảo thống nhất kết quả cuối cùng về kỹ thuật và mức độ đột phá.', status: 'upcoming' }
    ],
    timeline_phase4_title: 'Giai Đoạn 4: Kết Thúc & Trao Giải',
    timeline_phase4_desc: 'Hành trình tiếp diễn. Công bố giải thưởng chính thức, mở ra cơ hội ươm tạo sản phẩm và kết nối cộng đồng cho các giải pháp tác tử xuất sắc nhất.',
    timeline_phase4_date: 'Kết thúc sự kiện',
    timeline_phase4_location: 'Hội trường lớn & Digital Twin',
    timeline_phase4_items: [
      { time: '06:00 CH', title: 'Lễ bế mạc', detail: 'Tổng kết sự kiện, các bài học giá trị và hé lộ lộ trình phát triển tiếp theo của Aevum.', status: 'upcoming' },
      { time: '07:30 CH', title: 'Lễ trao giải', detail: 'Vinh danh những nhà xây dựng hàng đầu, các giải thưởng bình chọn từ cộng đồng và trao thưởng.', isSpecial: true, status: 'upcoming' },
      { time: '09:00 CH', title: 'Ký kết Ươm tạo', detail: 'Kết nối trực tiếp với các nhà đầu tư và quỹ tăng tốc để đưa sản phẩm ra thị trường.', status: 'upcoming' }
    ],
    timeline_phase5_title: 'Giai Đoạn 5: Bình Chọn Cộng Đồng',
    timeline_phase5_desc: 'Hành trình vươn xa cùng cộng đồng toàn cầu. Các sản phẩm tiếp tục tham gia bình chọn trên nền tảng Unikorn để nhận các phần quà và cơ hội hấp dẫn.',
    timeline_phase5_date: 'Sau sự kiện',
    timeline_phase5_location: 'Nền tảng Unikorn',
    timeline_phase5_items: [
      { time: 'Tuần 1-2', title: 'Bình chọn trên Unikorn', detail: 'Sản phẩm tiếp tục tham gia bình chọn trên Unikorn để nhận các phần quà hấp dẫn và sự ủng hộ từ cộng đồng.', isSpecial: true },
      { time: 'Hàng tháng', title: 'Builder Updates', detail: 'Duy trì kết nối và theo dõi các cột mốc phát triển tiếp theo của sản phẩm trong hệ sinh thái.' }
    ],
    reg_title: 'Tham gia',
    reg_subtitle: 'Đăng ký để trở thành một Builder thực thụ.',
    reg_label_name: 'Họ và Tên',
    reg_placeholder_name: 'Nguyễn Văn A',
    reg_label_email: 'Email',
    reg_placeholder_email: 'an@haevthon.com',
    reg_label_role: 'Vai trò',
    reg_placeholder_role: 'Chọn...',
    reg_label_experience: 'Kinh nghiệm',
    reg_placeholder_experience: 'Chọn...',
    reg_label_interest: 'Định hướng dự án',
    reg_placeholder_interest: 'Chia sẻ ngắn gọn về ý tưởng hoặc kỹ năng bạn muốn đóng góp...',
    reg_btn_submit: 'Xác nhận Đăng ký',
    reg_btn_submitting: 'Đang gửi...',
    reg_success: 'Đăng ký thành công! Chào mừng bạn đến với Haevthon. 🚀',
    reg_success_title: 'Đã Nhận Đơn Đăng Ký',
    reg_success_desc: 'Cảm ơn bạn đã tham gia Haevthon. Đội ngũ của chúng tôi sẽ xem xét hồ sơ và liên hệ với bạn qua email trong thời gian sớm nhất.',
    reg_btn_close: 'Đóng',
    reg_placeholder_select: 'Chọn...',
    reg_placeholder_select_answer: 'Chọn câu trả lời',
    reg_placeholder_select_source: 'Chọn nguồn',
    reg_placeholder_select_goal: 'Chọn mục tiêu',
    reg_placeholder_select_status: 'Chọn trạng thái',
    reg_placeholder_select_role: 'Chọn vai trò',
    reg_placeholder_select_level: 'Chọn mức độ',
    reg_placeholder_select_country: 'Chọn quốc gia',
    reg_placeholder_select_city: 'Chọn tỉnh thành',
    err_name_min: 'Họ và tên phải có ít nhất 2 ký tự',
    err_email_invalid: 'Email không hợp lệ',
    err_role_required: 'Vui lòng chọn vai trò',
    err_experience_required: 'Vui lòng chọn kinh nghiệm',
    err_interest_min: 'Vui lòng mô tả chi tiết hơn định hướng của bạn (ít nhất 10 ký tự)',
    err_discord_required: 'Vui lòng nhập Discord ID',
    err_linkedin_invalid: 'LinkedIn URL không hợp lệ',
    err_github_invalid: 'Github/Portfolio URL không hợp lệ',
    err_facebook_invalid: 'Facebook URL không hợp lệ',
    err_team_required: 'Vui lòng nhập tên đội',
    err_skills_required: 'Vui lòng nhập kỹ năng chính',
    err_age_numeric: 'Tuổi phải là số',
    reg_discord_label: 'DISCORD ID',
    reg_discord_ph: 'username#1234',
    reg_age_label: 'TUỔI',
    reg_gender_label: 'GIỚI TÍNH',
    reg_gender_male: 'Nam',
    reg_gender_female: 'Nữ',
    reg_gender_other: 'Khác',
    reg_linkedin_label: 'LINKEDIN URL (TÙY CHỌN)',
    reg_github_label: 'GITHUB / PORTFOLIO',
    reg_facebook_label: 'FACEBOOK URL (TÙY CHỌN)',
    reg_country_label: 'QUỐC GIA',
    reg_city_label: 'TỈNH THÀNH',
    reg_location_label: 'ĐƠN VỊ HỌC TẬP HOẶC LÀM VIỆC (NẾU CÓ)',
    reg_placeholder_residence: 'Trường ĐH / Công ty...',
    reg_exp_student_hs: 'Học sinh (Trung học)',
    reg_exp_student_uni: 'Sinh viên (Đại học)',
    reg_exp_fresher: 'Mới tốt nghiệp / Thực tập',
    reg_exp_junior: 'Junior (1-2 năm)',
    reg_exp_mid: 'Mid-level (3-5 năm)',
    reg_exp_senior: 'Senior (5+ năm)',
    reg_exp_expert: 'Lead / Chuyên gia',
    reg_role_ai: 'Kỹ sư AI',
    reg_role_fullstack: 'Lập trình viên Fullstack',
    reg_role_designer: 'Thiết kế sản phẩm',
    reg_role_manager: 'Quản trị sản phẩm',
    reg_survey_title: 'KHẢO SÁT TIỀN ĐĂNG KÝ',
    reg_survey_subtitle: 'Vui lòng trả lời vài câu hỏi ngắn để chúng tôi chuẩn bị tốt nhất.',
    reg_survey_q1: 'Bạn đã từng tham gia cuộc thi Hackathon nào trước đây chưa?',
    reg_survey_q1_yes: 'Rồi, mình đã từng tham gia',
    reg_survey_q1_no: 'Chưa, đây là lần đầu tiên của mình',
    reg_survey_q2: 'Bạn biết đến Haevthon qua kênh nào?',
    reg_survey_q2_social: 'Mạng xã hội (Facebook, LinkedIn, ...)',
    reg_survey_q2_friend: 'Bạn bè / Đồng nghiệp giới thiệu',
    reg_survey_q2_community: 'Cộng đồng công nghệ / Câu lạc bộ',
    reg_survey_q2_other: 'Nguồn khác',
    reg_survey_q3: 'Mục tiêu tham gia Haevthon của bạn là gì?',
    reg_survey_q3_learn: 'Học hỏi & Xây dựng sản phẩm',
    reg_survey_q3_net: 'Kết nối mạng lưới (Networking)',
    reg_survey_q3_prize: 'Chinh phục giải thưởng',
    reg_survey_q3_job: 'Tìm kiếm cơ hội việc làm',
    reg_survey_q4_label: 'BẠN ĐANG TÌM KIẾM ĐỒNG ĐỘI?',
    reg_survey_q4_yes: 'Có, tôi đang tìm đồng đội',
    reg_survey_q4_no: 'Không, tôi đã có đội rồi',
    reg_survey_q4_solo: 'Tôi muốn thi đấu cá nhân',
    reg_survey_q5_label: 'VAI TRÒ CHÍNH CỦA BẠN?',
    reg_survey_q5_dev: 'Lập trình viên (Fullstack/FE/BE)',
    reg_survey_q5_ai: 'Kỹ sư AI / Machine Learning',
    reg_survey_q5_design: 'Thiết kế UI/UX / Creative',
    reg_survey_q5_biz: 'Quản trị sản phẩm / Kinh doanh',
    reg_survey_q8_label: 'CÔNG NGHỆ / CÔNG CỤ AI QUAN TÂM',
    reg_survey_q9_label: 'MỨC ĐỘ VIBE CODING CỦA BẠN?',
    reg_survey_q9_new: 'Vibe coding là gì vậy?',
    reg_survey_q9_exploring: 'Đang làm quen với Vibes',
    reg_survey_q9_coder: 'Vibe Coder thực thụ',
    reg_survey_q9_master: 'Master of Vibes',
    reg_survey_q10_label: 'TINH THẦN AEVUMMAS CỦA BẠN?',
    reg_survey_q10_new: 'Mới biết đến Aevum',
    reg_survey_q10_fan: 'Đang theo dõi / Fan',
    reg_survey_q10_true: 'True Aevummas',
    reg_btn_next: 'TIẾP THEO',
    reg_btn_back_survey: 'QUAY LẠI KHẢO SÁT',
    reg_skills_label: 'KỸ NĂNG / TECH STACK',
    reg_team_label: 'TÊN ĐỘI / DỰ ÁN',
    reg_bio_label: 'ĐỊNH HƯỚNG DỰ ÁN / GIỚI THIỆU BẢN THÂN',
    reg_type_individual: 'CÁ NHÂN',
    reg_type_team: 'ĐĂNG KÝ ĐỘI',
    powered_by: 'Phát Triển Bởi Aevum',
    stats_prizepool: 'Tổng Giải Thưởng',
    stats_format: 'Hình Thức',
    stats_timeline: 'Lịch Trình',
    stats_format_val: 'Trực Tuyến',
    stats_timeline_val: 'Sắp Ra Mắt',
    status_upcoming: 'Sắp diễn ra',
    status_active: 'Đang diễn ra',
    status_done: 'Đã kết thúc',
    nav_sponsors: 'TÀI TRỢ',
    sponsors_partnership_opp: 'CƠ HỘI HỢP TÁC',
    sponsors_hero_title1: 'KIẾN TẠO',
    sponsors_hero_title2: 'KỶ NGUYÊN',
    sponsors_hero_title3: 'AI AGENT',
    sponsors_hero_desc: 'Haevthon 2026 là nơi thế hệ hệ thống AI tự chủ tiếp theo ra đời. Trở thành đối tác và khẳng định vị thế thương hiệu của bạn tại tiền tuyến của trí tuệ nhân tạo Agentic.',
    sponsors_hero_btn: 'TRỞ THÀNH NHÀ TÀI TRỢ',
    sponsors_hosted_by: 'ĐƠN VỊ TỔ CHỨC',
    sponsors_org_committee: 'BAN TỔ CHỨC',
    sponsors_obj_title: 'TẦM NHÌN CHUNG',
    sponsors_obj_heading: 'KIẾN TẠO TƯƠNG LAI',
    sponsors_obj_desc: 'Haevthon 2026 không chỉ là một cuộc thi, mà là một bệ phóng chiến lược. Chúng tôi tìm kiếm những đối tác có chung tầm nhìn để phá vỡ mọi giới hạn của AI tự chủ. Cùng nhau, chúng ta sẽ cung cấp tài nguyên, nền tảng và sự cố vấn cần thiết để hiện thực hóa những tham vọng lớn lao nhất.',
    sponsors_obj_list1_title: 'Định hình Công nghệ',
    sponsors_obj_list1_desc: 'Hợp tác thiết lập các tiêu chuẩn và framework mới cho hệ thống AI Agentic.',
    sponsors_obj_list2_title: 'Ươm mầm Tài năng',
    sponsors_obj_list2_desc: 'Tiếp cận trực tiếp và hỗ trợ mạng lưới những kỹ sư và nhà nghiên cứu tinh hoa.',
    sponsors_obj_list3_title: 'Đẩy mạnh Đổi mới',
    sponsors_obj_list3_desc: 'Góp phần biến những ý tưởng đột phá thành sản phẩm thực tế có tính ứng dụng cao.',
    sponsors_unikorn_desc: 'Đối tác Chiến lược. Tiếp sức cho thế hệ nhà kiến tạo tương lai.',
    sponsors_i2flabs_desc: 'Đơn vị Tổ chức & Trung tâm Đổi mới. Dẫn dắt tương lai công nghệ Agentic.',
    sponsors_aevum_desc: 'Đồng Tổ chức & Đối tác Công nghệ. Nền tảng lõi cho các hệ thống AI tự chủ.',
    sponsors_stats_title: 'NHỮNG CON SỐ',
    sponsors_why_title: 'TẠI SAO NÊN ĐỒNG HÀNH',
    sponsors_why_label1: 'Kỹ sư Tinh hoa',
    sponsors_why_desc1: 'Quy tụ những lập trình viên, nhà thiết kế và nhà nghiên cứu AI hàng đầu.',
    sponsors_why_label2: 'Tổng Giải thưởng',
    sponsors_why_desc2: 'Các đội thi nghiêm túc xây dựng sản phẩm AI Agent thực tế.',
    sponsors_why_label3: 'Giờ Lập trình',
    sponsors_why_desc3: 'Định dạng cường độ cao tạo ra MVP thực tế — không chỉ là ý tưởng.',
    sponsors_why_label4: 'Tập trung AI Agent',
    sponsors_why_desc4: 'Cuộc thi Hackathon chuyên sâu về AI nhất Đông Nam Á.',
    sponsors_contact_title: 'LIÊN HỆ',
    sponsors_contact_heading1: 'CÙNG NHAU',
    sponsors_contact_heading2: 'KIẾN TẠO',
    sponsors_contact_desc: 'Quan tâm đến việc tài trợ Haevthon 2026? Hãy liên hệ và đội ngũ đối tác của chúng tôi sẽ kết nối với bạn trong vòng 24 giờ để thảo luận về gói tài trợ phù hợp nhất.',
    sponsors_form_success_title: 'Đã Nhận Thông Tin',
    sponsors_form_success_desc: 'Cảm ơn bạn đã quan tâm. Đội ngũ của chúng tôi sẽ liên hệ trong vòng 24 giờ.',
    sponsors_form_name: 'Họ và tên',
    sponsors_form_name_ph: 'Nguyễn Văn A',
    sponsors_form_company: 'Công ty / Tổ chức (Tùy chọn)',
    sponsors_form_company_ph: 'Acme Corp / Nhà tài trợ cá nhân',
    sponsors_form_email: 'Email',
    sponsors_form_email_ph: 'partner@company.com',
    sponsors_form_interest: 'Nội dung quan tâm',
    sponsors_form_interest_ph: 'Chia sẻ với chúng tôi về sự quan tâm tài trợ và mức ngân sách dự kiến của bạn...',
    sponsors_form_submit: 'GỬI YÊU CẦU',
    contact_email: 'hainguyen0112358@gmail.com',
    contact_phone: '+84 (0) 879 29 9627',
    contact_address: 'TP. Hồ Chí Minh, Việt Nam',
    contact_website: 'i2flabs.unikorn.vn',
    powered_by_prefix: 'PHÁT TRIỂN BỞI',
    about_badge: 'TẦM NHÌN',
    about_title_part1: 'HAEVTHON',
    about_title_part2: 'KIẾN TẠO',
    about_title_part3: 'TỰ CHỦ',
    about_desc: "Haevthon là đấu trường hàng đầu thế giới cho các Hệ thống Tác tử Nâng cao. Chúng tôi không chỉ viết code; chúng tôi điều phối trí tuệ. Sứ mệnh của chúng tôi là tiếp sức cho thế hệ nhà kiến tạo tiếp theo vượt xa khỏi tự động hóa tĩnh để bước vào kỷ nguyên của các bầy đàn tác tử tự chủ thực thụ.",
    about_core_title: 'LÕI TÁC TỬ',
    about_core_desc: 'Xây dựng logic nền tảng cho các tác tử AI tự chủ có khả năng suy nghĩ và hành động.',
    about_swarm_title: 'TRÍ TUỆ BẦY ĐÀN',
    about_swarm_desc: 'Khám phá sự cộng tác đa tác tử, nơi các tác tử cùng nhau giải quyết các nhiệm vụ phức tạp.',
    about_cta: 'TÌM HIỂU THÊM VỀ SỨ MỆNH',
    about_card_title: 'HAEVTHON 2026',
    about_card_desc: 'Điểm đến hàng đầu cho các nhà kiến tạo tác tử tiên phong trên toàn thế giới.',
    innovation_title_part1: 'DẪN DẦU LÀN SÓNG',
    innovation_title_part2: 'ĐỔI MỚI',
    innovation_title_part3: 'SÁNG TẠO',
    innovation_desc_main: 'Việt Nam đang nhanh chóng trở thành trung tâm phát triển AI toàn cầu. Haevthon được thiết kế để tiếp sức cho tài năng Việt xây dựng các Giải pháp Tác tử đẳng cấp thế giới.',
    innovation_item1_title: 'THÚC ĐẨY TĂNG TRƯỞNG',
    innovation_item1_desc: 'Hackathon là động cơ tạo mẫu nhanh, biến các ý tưởng táo bạo thành startup tiềm năng.',
    innovation_item2_title: 'KỶ NGUYÊN AI VIỆT NAM',
    innovation_item2_desc: 'Với hệ sinh thái bùng nổ, Việt Nam đang trở thành cường quốc công nghệ tại Đông Nam Á.',
    innovation_item3_title: 'KIẾN TẠO TƯƠNG LAI',
    innovation_item3_desc: 'Haevthon là phong trào tiếp sức cho thế hệ những nhà xây dựng toàn cầu tiếp theo.',
    vision_score_exec: 'Kỹ năng thực thi',
    vision_score_product: 'Tư duy sản phẩm',
    vision_score_util: 'Ứng dụng Aevum',
    vision_score_innov: 'Tính sáng tạo',
    footer_desc: 'Tiếp sức cho thế hệ hệ thống AI tự chủ tiếp theo. Xây dựng bởi các builder, dành cho các builder.',
    footer_explore: 'Khám phá',
    footer_connect: 'Kết nối',
    footer_privacy: 'Chính sách bảo mật',
    footer_terms: 'Điều khoản dịch vụ',
    footer_rights: 'Bảo lưu mọi quyền.'
  }
};
